# Generated by Django 6.0.2 on 2026-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Device')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Serial-Number')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP Address')),
                ('opc_server_port', models.PositiveIntegerField(blank=True, default=0, verbose_name='OPC Server Port')),
                ('device_type', models.IntegerField(choices=[(0, 'Generic Device'), (1, 'OPC UA GDS'), (2, 'OPC UA GDS Push')], default=0, verbose_name='Device Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('opc_gds_push_enable_periodic_update', models.BooleanField(blank=True, default=False, help_text='When enabled, the server certificate and trustlist will be automatically renewed at the specified interval.', verbose_name='Enable Periodic Certificate and Trustlist Update')),
                ('opc_gds_push_renewal_interval', models.PositiveIntegerField(blank=True, default=168, help_text='Number of hours between each automatic server certificate and trustlist renewal. Minimum 1 hour.', verbose_name='Renewal Interval (hours)')),
                ('opc_gds_push_last_update_scheduled_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent scheduled periodic server certificate and trustlist update.', null=True, verbose_name='Last Periodic Update Scheduled At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssuedCredentialModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=255, verbose_name='Common Name')),
                ('issued_credential_type', models.IntegerField(choices=[(0, 'Domain Credential'), (1, 'Application Credential')], verbose_name='Credential Type')),
                ('issued_using_cert_profile', models.CharField(default='', max_length=255, verbose_name='Issued using Certificate Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteDeviceCredentialDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='', max_length=32, verbose_name='OTP')),
                ('attempts', models.IntegerField(default=0, verbose_name='Attempts')),
                ('download_token', models.CharField(default='', max_length=64, verbose_name='Download Token')),
                ('token_created_at', models.DateTimeField(null=True, verbose_name='Token Created')),
            ],
        ),
    ]
