# Generated by Django 5.2.4 on 2025-09-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='onboarding_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Onboarded')], default=1, verbose_name='Onboarding Status'),
        ),
    ]
