# Generated by Django 5.1.9 on 2025-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='pki_protocol',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='allowed_pki_protocols',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Pki Protocol Bitwise Flag'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='no_onboarding_pki_protocol',
            field=models.PositiveIntegerField(choices=[(0, 'Onboarding'), (1, 'Manual Download'), (2, 'EST - Username & Password'), (3, 'CMP - Shared Secret')], default=3, verbose_name='PKI Protocol'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='cmp_shared_secret',
            field=models.CharField(default='', max_length=128, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='common_name',
            field=models.CharField(default='', max_length=100, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='est_password',
            field=models.CharField(default='', max_length=128, verbose_name='EST Password'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='onboarding_protocol',
            field=models.PositiveIntegerField(choices=[(0, 'No Onboarding'), (1, 'Manual Onboarding'), (2, 'CMP - IDevID'), (3, 'CMP - Shared Secret'), (4, 'EST - IDevID'), (5, 'EST - Username & Password'), (6, 'AOKI'), (7, 'BRSKI')], default=0, verbose_name='Onboarding Protocol'),
        ),
    ]
