# Generated by Django 5.1.9 on 2025-09-16 09:41

import util.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
    ]
