# Generated by Django 5.2.4 on 2025-07-18 12:54

import devices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0001_initial'),
        ('pki', '0002_tp_v0_3_0_dev0'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoOnboardingConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'pki_protocols',
                    models.PositiveIntegerField(blank=True, default=0, verbose_name='Pki Protocol Bitwise Flag'),
                ),
                (
                    'est_username_password',
                    models.CharField(blank=True, default='', max_length=128, verbose_name='EST Password'),
                ),
                (
                    'cmp_shared_secret',
                    models.CharField(blank=True, default='', max_length=128, verbose_name='CMP Shared Secret'),
                ),
            ],
            bases=(devices.models.AbstractPkiProtocolModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='cmp_shared_secret',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='domain_credential_onboarding',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='est_password',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='idevid_trust_store',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='onboarding_protocol',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='onboarding_status',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='pki_protocol',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='common_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='no_onboarding_config',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='device',
                to='devices.noonboardingconfigmodel',
                verbose_name='No Onboarding Config',
            ),
        ),
        migrations.CreateModel(
            name='OnboardingConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pki_protocols', models.PositiveIntegerField(verbose_name='Pki Protocol Bitwise Flag')),
                (
                    'onboarding_status',
                    models.IntegerField(choices=[(1, 'Pending'), (2, 'Onboarded')], verbose_name='Onboarding Status'),
                ),
                (
                    'onboarding_protocol',
                    models.PositiveIntegerField(
                        choices=[
                            (0, 'Manual Onboarding'),
                            (1, 'CMP - IDevID'),
                            (2, 'CMP - Shared Secret'),
                            (3, 'EST - IDevID'),
                            (4, 'EST - Username & Password'),
                            (5, 'AOKI'),
                            (6, 'BRSKI'),
                        ],
                        verbose_name='Onboarding Protocol',
                    ),
                ),
                (
                    'onboarding_est_password',
                    models.CharField(blank=True, default='', max_length=128, verbose_name='EST Password'),
                ),
                (
                    'onboarding_cmp_shared_secret',
                    models.CharField(blank=True, default='', max_length=128, verbose_name='CMP Shared Secret'),
                ),
                (
                    'idevid_trust_store',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='pki.truststoremodel',
                        verbose_name='IDevID Manufacturer Truststore',
                    ),
                ),
            ],
            bases=(devices.models.AbstractPkiProtocolModel, models.Model),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='onboarding_config',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='device',
                to='devices.onboardingconfigmodel',
                verbose_name='Onboarding Config',
            ),
        ),
    ]
