# Generated by Django 5.0.1 on 2024-02-19 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='certificate',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
