# Generated by Django 5.2.8 on 2025-12-08 09:27

import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcredentialmodel',
            name='issued_credential_purpose',
        ),
        migrations.AddField(
            model_name='issuedcredentialmodel',
            name='issued_using_cert_profile',
            field=models.CharField(default='', max_length=255, verbose_name='Issued using Certificate Profile'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
    ]
