# Generated by Django 6.0.2 on 2026-03-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcredentialmodel',
            name='credential',
        ),
        migrations.RemoveField(
            model_name='issuedcredentialmodel',
            name='device',
        ),
        migrations.RemoveField(
            model_name='issuedcredentialmodel',
            name='domain',
        ),
    ]
