# Generated by Django 5.2.8 on 2025-12-09 10:48

import util.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_tp_v0_4_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
    ]
