# Generated by Django 5.2.8 on 2026-01-29 14:29

import django.db.models.deletion
import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_tp_v0_4_0'),
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='opc_server_port',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='OPC Server Port'),
        ),
        migrations.AddField(
            model_name='onboardingconfigmodel',
            name='opc_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='OPC Password'),
        ),
        migrations.AddField(
            model_name='onboardingconfigmodel',
            name='opc_trust_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opc_onboarding_configs', to='pki.truststoremodel', verbose_name='OPC Server Truststore'),
        ),
        migrations.AddField(
            model_name='onboardingconfigmodel',
            name='opc_user',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='OPC User'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'Generic Device'), (1, 'OPC UA GDS'), (2, 'OPC UA GDS Push')], default=0, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='idevid_trust_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idevid_onboarding_configs', to='pki.truststoremodel', verbose_name='IDevID Manufacturer Truststore'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='onboarding_protocol',
            field=models.PositiveIntegerField(choices=[(0, 'Manual Onboarding'), (1, 'CMP - IDevID'), (2, 'CMP - Shared Secret'), (3, 'EST - IDevID'), (4, 'EST - Username & Password'), (5, 'AOKI'), (6, 'BRSKI'), (7, 'OPC - GDS Push')], verbose_name='Onboarding Protocol'),
        ),
    ]
