# Generated by Django 6.0.2 on 2026-02-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_tp_v0_5_0_dev1'),
        ('pki', '0004_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcredentialmodel',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='pki.camodel', verbose_name='CA'),
        ),
        migrations.AddField(
            model_name='issuedcredentialmodel',
            name='owner_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='pki.ownercredentialmodel', verbose_name='Owner Credential'),
        ),
        migrations.AlterField(
            model_name='issuedcredentialmodel',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='devices.devicemodel', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='issuedcredentialmodel',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='pki.domainmodel', verbose_name='Domain'),
        ),
    ]
