# Generated by Django 6.0.2 on 2026-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='opc_gds_push_enable_periodic_update',
            field=models.BooleanField(blank=True, default=False, help_text='When enabled, the server certificate and trustlist will be automatically renewed at the specified interval.', verbose_name='Enable Periodic Certificate and Trustlist Update'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='opc_gds_push_last_update_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent scheduled periodic server certificate and trustlist update.', null=True, verbose_name='Last Periodic Update Scheduled At'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='opc_gds_push_renewal_interval',
            field=models.PositiveIntegerField(blank=True, default=168, help_text='Number of hours between each automatic server certificate and trustlist renewal. Minimum 1 hour.', verbose_name='Renewal Interval (hours)'),
        ),
    ]
