# Generated by Django 5.2.8 on 2026-01-22 08:43

import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='port',
            new_name='opc_server_port',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='opc_server_port',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='OPC Server Port'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='opc_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='OPC Password'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='opc_user',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='OPC User'),
        ),
    ]
