# Generated by Django 5.2.8 on 2026-02-09 14:09

import django.db.models.deletion
import trustpoint.logger
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_tp_v0_5_0_dev1'),
        ('pki', '0001_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=17)),
                ('container_id', models.CharField(blank=True, default='', help_text='Container build ID or hash', max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Version',
            },
        ),
        migrations.CreateModel(
            name='BackupOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_sftp_storage', models.BooleanField(default=False, verbose_name='Use SFTP storage')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host')),
                ('port', models.PositiveIntegerField(blank=True, default=2222, verbose_name='Port')),
                ('user', models.CharField(blank=True, max_length=128, verbose_name='Username')),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH Key')], default='password', max_length=10, verbose_name='Authentication Method')),
                ('password', models.CharField(blank=True, help_text='Plain-text password for SFTP.', max_length=128, verbose_name='Password')),
                ('private_key', models.TextField(blank=True, help_text='Paste the private key here (PEM).', verbose_name='SSH Private Key (PEM format)')),
                ('key_passphrase', models.CharField(blank=True, help_text='Passphrase for the private key, if any.', max_length=128, verbose_name='Key Passphrase')),
                ('remote_directory', models.CharField(blank=True, default='/upload/trustpoint/', help_text='Remote directory (e.g. /backups/) where files should be uploaded. Trailing slash is optional.', max_length=512, verbose_name='Remote Directory')),
            ],
            options={
                'verbose_name': 'Backup Option',
            },
        ),
        migrations.CreateModel(
            name='LoggingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('0', 'Debug'), ('1', 'Info'), ('2', 'Warning'), ('3', 'Error'), ('4', 'Critical')], default='1', max_length=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TlsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='PKCS11Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Token label in SoftHSM', max_length=100, unique=True, verbose_name='Label')),
                ('slot', models.PositiveIntegerField(help_text='Slot number in SoftHSM', verbose_name='Slot')),
                ('module_path', models.CharField(default='/usr/local/lib/libpkcs11-proxy.so', help_text='Path to PKCS#11 module library', max_length=255, verbose_name='Module Path')),
                ('encrypted_dek', models.BinaryField(blank=True, help_text='Symmetric key encrypted by the PKCS#11 private key', max_length=512, null=True, verbose_name='Encrypted Data Encryption Key (DEK)')),
                ('bek_encrypted_dek', models.BinaryField(blank=True, help_text='Symmetric key encrypted by the PKCS#11 private key', max_length=512, null=True, verbose_name='Encrypted Data Encryption Key (DEK)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('kek', models.ForeignKey(blank=True, help_text='Associated key encryption key stored in this token', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pki.pkcs11key', verbose_name='Key Encryption Key (KEK)')),
            ],
            options={
                'verbose_name': 'PKCS#11 Token',
                'verbose_name_plural': 'PKCS#11 Tokens',
            },
            bases=(models.Model, trustpoint.logger.LoggerMixin),
        ),
        migrations.CreateModel(
            name='KeyStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('software', 'Software (No Encryption)'), ('softhsm', 'SoftHSM Container'), ('physical_hsm', 'Physical HSM')], default='software', help_text='Type of storage for cryptographic material', max_length=12, verbose_name='Storage Type')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('hsm_config', models.OneToOneField(blank=True, help_text='Associated HSM token configuration (SoftHSM or Physical HSM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_storage_config', to='management.pkcs11token', verbose_name='HSM Configuration')),
            ],
            options={
                'verbose_name': 'Crypto Storage Configuration',
                'verbose_name_plural': 'Crypto Storage Configurations',
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_mode', models.CharField(choices=[('0', 'Testing env'), ('1', 'Basic'), ('2', 'Medium'), ('3', 'High'), ('4', 'Highest')], default='1', max_length=6)),
                ('auto_gen_pki', models.BooleanField(default=False)),
                ('auto_gen_pki_key_algorithm', models.CharField(choices=[('RSA2048SHA256', 'RSA2048'), ('RSA4096SHA256', 'RSA4096'), ('SECP256R1SHA256', 'SECP256R1')], default='RSA2048SHA256', max_length=24)),
                ('notification_config', models.OneToOneField(help_text='Notification configuration associated with this security level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_config', to='notifications.notificationconfig')),
            ],
        ),
    ]
