# Generated by Django 5.2.4 on 2025-09-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_tp_v0_3_0_dev1'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('0', 'Debug'), ('1', 'Info'), ('2', 'Warning'), ('3', 'Error'), ('4', 'Critical')], default='1', max_length=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
