# Generated by Django 5.2.7 on 2025-11-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupoptions',
            old_name='sftp_storage',
            new_name='enable_sftp_storage',
        ),
        migrations.RemoveField(
            model_name='backupoptions',
            name='local_storage',
        ),
        migrations.AlterField(
            model_name='backupoptions',
            name='password',
            field=models.CharField(blank=True, help_text='Encrypted password for SFTP.', max_length=128, verbose_name='Password'),
        ),
    ]
