# Generated by Django 5.1.9 on 2025-10-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_tp_v0_3_0_dev1'),
        ('notifications', '0001_tp_v0_3_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityconfig',
            name='notification_config',
            field=models.OneToOneField(help_text='Notification configuration associated with this security level.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_config', to='notifications.notificationconfig'),
        ),
    ]
