# Generated by Django 6.0.2 on 2026-02-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_tp_v0_5_0_dev1'),
        ('management', '0002_tp_v0_4_0'),
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable all notifications globally.')),
                ('notification_cycle_enabled', models.BooleanField(default=False, help_text='Enable automatic periodic notification checks via Django-Q2', verbose_name='Enable Notification Cycle Updates')),
                ('notification_cycle_interval_hours', models.FloatField(default=0.0833, help_text='The interval in hours between automatic notification checks (default: 5 minutes)', verbose_name='Notification Cycle Interval (hours)')),
                ('last_notification_check_started_at', models.DateTimeField(blank=True, help_text='Timestamp when the last notification check task was started', null=True, verbose_name='Last Notification Check Started')),
                ('cert_expiry_warning_days', models.PositiveIntegerField(default=30, help_text="Number of days before a certificate's expiration to trigger a 'Certificate Expiring' warning.")),
                ('issuing_ca_expiry_warning_days', models.PositiveIntegerField(default=30, help_text="Number of days before an issuing CA's certificate expiration to trigger a warning.")),
            ],
            options={
                'verbose_name': 'Notification Configuration',
            },
        ),
        migrations.CreateModel(
            name='NotificationMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(default='No description provided', max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONF', 'Confirmed'), ('PROG', 'In Progress'), ('SOLV', 'Solved'), ('NOSOL', 'Not Solved'), ('ESC', 'Escalated'), ('SUS', 'Suspended'), ('REJ', 'Rejected'), ('DEL', 'Deleted'), ('CLO', 'Closed'), ('ACK', 'Acknowledged'), ('FAIL', 'Failed'), ('EXP', 'Expired'), ('PEND', 'Pending')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeakECCCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(choices=[('1.3.132.0.8', 'SECP160R1'), ('1.2.840.10045.3.1.1', 'SECP192R1'), ('1.3.132.0.33', 'SECP224R1'), ('1.3.132.0.10', 'SECP256K1')], max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeakSignatureAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(choices=[('1.2.840.113549.2.5', 'MD5'), ('1.3.14.3.2.26', 'SHA-1'), ('2.16.840.1.101.3.4.2.4', 'SHA-224')], max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='allow_auto_gen_pki',
            field=models.BooleanField(default=False, help_text='Allow enabling the auto-generated PKI feature.'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='allow_ca_issuance',
            field=models.BooleanField(default=False, help_text='Allow issuance of certificates with BasicConstraints ca=True.'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='allow_self_signed_ca',
            field=models.BooleanField(default=False, help_text='Allow self-signed CAs to be imported with credentials.'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='max_cert_validity_days',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Maximum certificate validity period in days. Set to null for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='max_crl_validity_days',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Maximum CRL validity period in days. Set to null for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='not_permitted_ecc_curve_oids',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of ECC curve OIDs (from trustpoint_core.oid.NamedCurve) not permitted at the current security level.'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='not_permitted_signature_algorithm_oids',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of hash algorithm OIDs (from trustpoint_core.oid.HashAlgorithm) not permitted at the current security level.'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='permitted_no_onboarding_pki_protocols',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of allowed NoOnboardingPkiProtocol integer values (bitmask flags: CMP_SHARED_SECRET=1, EST_USERNAME_PASSWORD=4, MANUAL=16).'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='permitted_onboarding_protocols',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of allowed OnboardingProtocol integer values (MANUAL=0, CMP_IDEVID=1, CMP_SHARED_SECRET=2, EST_IDEVID=3, EST_USERNAME_PASSWORD=4, AOKI=5, BRSKI=6, OPC_GDS_PUSH=7).'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='require_physical_hsm',
            field=models.BooleanField(default=False, help_text='Require key storage to use a physical HSM (KeyStorageConfig.StorageType.PHYSICAL_HSM).'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='rsa_minimum_key_size',
            field=models.PositiveIntegerField(blank=True, default=2048, help_text='Minimum RSA key size in bits that certificates must meet. Set to 0 to allow any RSA key size. Set to null to disallow RSA entirely.', null=True),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='security_mode',
            field=models.CharField(choices=[('0', 'Lab / Development'), ('1', 'Brownfield Compatible'), ('2', 'Industrial Standard'), ('3', 'Hardened Production'), ('4', 'Critical Infrastructure')], default='1', max_length=6),
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SET', 'SETUP'), ('INF', 'INFO'), ('WAR', 'WARNING'), ('CRI', 'CRITICAL')], default='INF', max_length=3)),
                ('notification_source', models.CharField(choices=[('S', 'System'), ('D', 'Domain'), ('E', 'Device'), ('I', 'Issuing CA'), ('C', 'Certificate')], default='S', max_length=1)),
                ('message_type', models.CharField(choices=[('C', 'custom'), ('TEST_CA', 'Issuing Ca Test'), ('TEST_DOMAIN', 'Domain Test'), ('TEST_CERT', 'Cert Test'), ('TEST_DEVICE', 'Device Test'), ('POP_TEST_DATA', 'Welcome Populate Test Data'), ('TP_DOCS', 'Trustpoint Documentation'), ('TP_INFO', 'Trustpoint Project Info'), ('WELCOME', 'Welcome Message'), ('SYS_NOT_HEALTHY', 'System Not Healthy'), ('VULNERABILITY', 'Vulnerability'), ('CERT_EXPIRING', 'Cert Expiring'), ('CERT_EXPIRED', 'Cert Expired'), ('CA_EXPIRING', 'Issuing Ca Expiring'), ('CA_EXPIRED', 'Issuing Ca Expired'), ('DOMAIN_NO_CA', 'Domain No Issuing Ca'), ('DEV_NOT_ONBRD', 'Device Not Onboarded'), ('DEV_ONBRD_FAIL', 'Device Onboarding Failed'), ('DEV_CERT_REV', 'Device Cert Revoked'), ('WEAK_SIG_ALGO', 'Weak Signature Algorithm'), ('INSUFF_KEY_LEN', 'Insufficient Key Length'), ('WEAK_ECC_CURVE', 'Weak Ecc Curve')], default='C', max_length=32)),
                ('message_data', models.JSONField(blank=True, default=dict)),
                ('event', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pki.certificatemodel')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='devices.devicemodel')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pki.domainmodel')),
            ],
        ),
    ]
