# Generated by Django 5.2.6 on 2025-09-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_tp_v0_3_0_dev2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('software', 'Software (No Encryption)'), ('softhsm', 'SoftHSM Container'), ('physical_hsm', 'Physical HSM')], default='software', help_text='Type of storage for cryptographic material', max_length=12, verbose_name='Storage Type')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('physical_hsm_config', models.OneToOneField(blank=True, help_text='Associated physical HSM token configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_crypto_storage_config', to='management.pkcs11token', verbose_name='Physical HSM Configuration')),
                ('softhsm_config', models.OneToOneField(blank=True, help_text='Associated SoftHSM token configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_storage_config', to='management.pkcs11token', verbose_name='SoftHSM Configuration')),
            ],
            options={
                'verbose_name': 'Crypto Storage Configuration',
                'verbose_name_plural': 'Crypto Storage Configurations',
            },
        ),
    ]
