# Generated by Django 6.0.2 on 2026-02-27 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_tp_v0_5_0_dev1'),
        ('pki', '0003_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='issuing_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pki.camodel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='management.notificationmessagemodel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='statuses',
            field=models.ManyToManyField(related_name='notifications', to='management.notificationstatus'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='weak_ecc_curves',
            field=models.ManyToManyField(blank=True, help_text='Select ECC curves considered weak or deprecated.', to='management.weakecccurve'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='weak_signature_algorithms',
            field=models.ManyToManyField(blank=True, help_text='Select signature algorithms considered weak or deprecated.', to='management.weaksignaturealgorithm'),
        ),
    ]
