# Generated by Django 5.2.6 on 2025-09-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_tp_v0_3_0_dev2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkcs11token',
            name='hsm_type',
        ),
    ]
