# Generated by Django 5.2.6 on 2025-09-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_tp_v0_3_0_dev2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptostorageconfig',
            name='physical_hsm_config',
        ),
        migrations.RemoveField(
            model_name='cryptostorageconfig',
            name='softhsm_config',
        ),
        migrations.AddField(
            model_name='cryptostorageconfig',
            name='hsm_config',
            field=models.OneToOneField(blank=True, help_text='Associated HSM token configuration (SoftHSM or Physical HSM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_storage_config', to='management.pkcs11token', verbose_name='HSM Configuration'),
        ),
    ]
