# Generated by Django 5.2.8 on 2026-02-03 08:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow2Definition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('yaml_text', models.TextField()),
                ('ir_json', models.JSONField()),
                ('ir_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled'], name='workflows2__enabled_2128e4_idx'), models.Index(fields=['ir_hash'], name='workflows2__ir_hash_55d9ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Workflow2Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_json', models.JSONField()),
                ('vars_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('awaiting', 'Awaiting')], default='running', max_length=16)),
                ('current_step', models.CharField(blank=True, max_length=200, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows2.workflow2definition')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow2StepRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_index', models.PositiveIntegerField()),
                ('step_id', models.CharField(max_length=200)),
                ('step_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=16)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('next_step', models.CharField(blank=True, max_length=200, null=True)),
                ('vars_delta', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows2.workflow2instance')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflow2instance',
            index=models.Index(fields=['status'], name='workflows2__status_2afdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow2instance',
            index=models.Index(fields=['created_at'], name='workflows2__created_b79f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow2steprun',
            index=models.Index(fields=['instance', 'run_index'], name='workflows2__instanc_c347b2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow2steprun',
            index=models.Index(fields=['step_id'], name='workflows2__step_id_4cbee1_idx'),
        ),
    ]
