# Generated by Django 5.2.8 on 2026-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows2', '0001_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow2definition',
            name='trigger_on',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='workflow2definition',
            index=models.Index(fields=['trigger_on'], name='workflows2__trigger_c2c878_idx'),
        ),
    ]
