# Generated by Django 5.2.8 on 2026-02-03 16:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows2', '0002_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow2instance',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting', 'Awaiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='Workflow2Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('run', 'Run'), ('resume', 'Resume')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=6)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workflows2.workflow2instance')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'run_after'], name='workflows2__status_5f0b2f_idx'), models.Index(fields=['locked_until'], name='workflows2__locked__1f04a6_idx'), models.Index(fields=['instance', 'status'], name='workflows2__instanc_95feba_idx')],
            },
        ),
    ]
