# Generated by Django 5.2.8 on 2026-02-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows2', '0002_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow2job',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
