# Generated by Django 5.2.8 on 2026-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows2', '0003_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow2instance',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting', 'Awaiting'), ('succeeded', 'Succeeded'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
