# Generated by Django 5.2.8 on 2026-01-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_tp_v0_5_0_dev1'),
        ('pki', '0005_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereddevice',
            name='certificate_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_on_devices', to='pki.certificatemodel'),
        ),
    ]
