# Generated by Django 5.2.8 on 2026-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
