# Generated by Django 5.2.4 on 2025-09-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=30, unique=True)),
                ('signing_algorithm', models.CharField(choices=[('1.2.840.113549.1.1.4', 'RSA with MD5'), ('1.2.840.113549.1.1.5', 'RSA with SHA1'), ('1.3.14.3.2.29', 'RSA with SHA1'), ('1.2.840.113549.1.1.14', 'RSA with SHA224'), ('1.2.840.113549.1.1.11', 'RSA with SHA256'), ('1.2.840.113549.1.1.12', 'RSA with SHA384'), ('1.2.840.113549.1.1.13', 'RSA with SHA512'), ('2.16.840.1.101.3.4.3.13', 'RSA with SHA3-224'), ('2.16.840.1.101.3.4.3.14', 'RSA with SHA3-256'), ('2.16.840.1.101.3.4.3.15', 'RSA with SHA3-384'), ('2.16.840.1.101.3.4.3.16', 'RSA with SHA3-512'), ('1.2.840.10045.4.1', 'ECDSA with SHA1'), ('1.2.840.10045.4.3.1', 'ECDSA with SHA224'), ('1.2.840.10045.4.3.2', 'ECDSA with SHA256'), ('1.2.840.10045.4.3.3', 'ECDSA with SHA384'), ('1.2.840.10045.4.3.4', 'ECDSA with SHA512'), ('2.16.840.1.101.3.4.3.9', 'ECDSA with SHA3-224'), ('2.16.840.1.101.3.4.3.10', 'ECDSA with SHA3-256'), ('2.16.840.1.101.3.4.3.11', 'ECDSA with SHA3-384'), ('2.16.840.1.101.3.4.3.12', 'ECDSA with SHA3-512'), ('1.2.840.113533.7.66.13', 'Password Based MAC')], max_length=50)),
                ('key_length', models.IntegerField(blank=True, choices=[(2048, '2048 bits'), (3072, '3072 bits'), (4096, '4096 bits'), (8192, '8192 bits')], null=True)),
                ('curve', models.CharField(blank=True, choices=[('prime192v1', 'SECP192R1'), ('secp224r1', 'SECP224R1'), ('secp256k1', 'SECP256K1'), ('prime256v1', 'SECP256R1'), ('secp384r1', 'SECP384R1'), ('secp521r1', 'SECP521R1'), ('brainpoolP256r1', 'BRAINPOOLP256R1'), ('brainpoolP384r1', 'BRAINPOOLP384R1'), ('brainpoolP512r1', 'BRAINPOOLP512R1'), ('sect163r1', 'SECT163K1'), ('sect163r2', 'SECT163R2'), ('sect233k1', 'SECT233K1'), ('sect233r1', 'SECT233R1'), ('sect283k1', 'SECT283K1'), ('sect283r1', 'SECT283R1'), ('sect409k1', 'SECT409K1'), ('sect409r1', 'SECT409R1'), ('sect571k1', 'SECT571K1'), ('sect571r1', 'SECT571R1')], max_length=50, null=True)),
                ('hash_function', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=4096)),
                ('certificate', models.CharField(max_length=4096)),
                ('expires_by', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_subject', models.TextField()),
                ('hash_value', models.CharField(max_length=256)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_messages', to='signer.signer')),
            ],
        ),
    ]
