# Generated by Django 5.2.7 on 2025-11-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_tp_v0_4_0_dev1'),
        ('signer', '0001_tp_v0_3_0_dev2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signer', to='pki.credentialmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignedMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_public_bytes', models.CharField(editable=False, max_length=2048, verbose_name='Signer Public Bytes')),
                ('hash_value', models.CharField(max_length=256)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_messages', to='signer.signermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='SignedMessage',
        ),
        migrations.DeleteModel(
            name='Signer',
        ),
    ]
