services:
  trustpoint:
    build:
      context: .
      dockerfile: docker/trustpoint/Dockerfile
    image: trustpointproject/trustpoint:latest
    container_name: trustpoint
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      postgres:
        condition: service_started
      softhsm:
        condition: service_healthy
    volumes:
      - ./trustpoint/settings:/var/www/html/trustpoint/trustpoint/settings
      - softhsm_config:/var/lib/trustpoint/hsm/config
      - softhsm_tokens:/var/lib/trustpoint/hsm/tokens
    environment:
      POSTGRES_DB: "trustpoint_db"
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      HSM_PIN_FILE: /run/secrets/hsm_pin
      HSM_SO_PIN_FILE: /run/secrets/hsm_so_pin
      TRUSTPOINT_HSM_ROOT: /var/lib/trustpoint/hsm
      SOFTHSM2_CONF: /var/lib/trustpoint/hsm/config/softhsm2.conf
      TRUSTPOINT_LOCAL_HSM_ENABLED: "1"
      TRUSTPOINT_LOCAL_HSM_TOKEN_LABEL: Trustpoint-SoftHSM
      TRUSTPOINT_LOCAL_HSM_PROFILE_NAME: local-dev-softhsm
      TRUSTPOINT_LOCAL_HSM_MODULE_PATH: /usr/lib/libsofthsm2.so
      TRUSTPOINT_LOCAL_HSM_USER_PIN_FILE: /var/lib/trustpoint/hsm/config/user-pin.txt
      TRUSTPOINT_LOCAL_HSM_CONFIG_ENV_VAR: SOFTHSM2_CONF
      TRUSTPOINT_LOCAL_HSM_SOFTHSM2_CONF: /var/lib/trustpoint/hsm/config/softhsm2.conf
    secrets:
      - db_user
      - db_password
      - hsm_pin
      - hsm_so_pin

  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: trustpointproject/postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: "trustpoint_db"
    secrets:
      - db_user
      - db_password

  softhsm:
    build:
      context: .
      dockerfile: docker/softhsm/Dockerfile
    container_name: softhsm
    ports:
      - "5657:5657"
    volumes:
      - softhsm_config:/var/lib/trustpoint/hsm/config
      - softhsm_tokens:/var/lib/trustpoint/hsm/tokens
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5657"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt
  hsm_pin:
    file: hsm_pin.txt
  hsm_so_pin:
    file: hsm_so_pin.txt


volumes:
  postgres_data:
  softhsm_config:
  softhsm_tokens:
