services:
  trustpoint:
    build:
      context: .
      dockerfile: docker/trustpoint/Dockerfile
    image: trustpointproject/trustpoint:latest
    container_name: trustpoint
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - softhsm
    volumes:
      - ./trustpoint/settings:/var/www/html/trustpoint/trustpoint/settings
    environment:
      POSTGRES_DB: "trustpoint_db"
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      HSM_PIN_FILE: /run/secrets/hsm_pin
      HSM_SO_PIN_FILE: /run/secrets/hsm_so_pin
      PKCS11_PROXY_SOCKET: "softhsm:5657"
    secrets:
      - db_user
      - db_password
      - hsm_pin
      - hsm_so_pin

  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: trustpointproject/postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: "trustpoint_db"
    secrets:
      - db_user
      - db_password

  softhsm:
    build:
      context: .
      dockerfile: docker/softhsm/Dockerfile
    container_name: softhsm
    ports:
      - "5657:5657"

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt
  hsm_pin:
    file: hsm_pin.txt
  hsm_so_pin:
    file: hsm_so_pin.txt


volumes:
  postgres_data:
