[mypy]
strict = True
plugins = mypy_django_plugin.main
mypy_path = trustpoint
python_version = 3.13
exclude = ^(var/|trustpoint/manage\.py$|tests/|.*/tests/|migrations/|.*/migrations/|trustpoint/features/steps/.*$|trustpoint/tests/.*$|trustpoint/pki/management/commands/add_domains_and_devices\.py$|trustpoint/pki/management/commands/base_commands\.py$|trustpoint/pki/management/commands/create_and_validate_test_certs\.py$|trustpoint/pki/management/commands/create_ca_issuer_setup\.py$|trustpoint/pki/management/commands/create_multiple_test_issuing_cas\.py$|trustpoint/pki/management/commands/create_protocol_test_env\.py$|trustpoint/pki/management/commands/create_ra_setup\.py$|trustpoint/pki/management/commands/create_test_long_chain_p12\.py$|trustpoint/pki/management/commands/reset_db\.py$|trustpoint/pki/management/commands/runserver_with_qcluster\.py$|trustpoint/management/management/commands/.*$|trustpoint/management/security/.*$|trustpoint/features/environment\.py$|conftest\.py$|.*/conftest\.py$)

# Tell the django-stubs plugin where settings.py lives:
[mypy.plugins.django-stubs]
django_settings_module = trustpoint.settings

# Per-module overrides (ignore missing imports for crispy apps):
[mypy-crispy_bootstrap5.*]
ignore_missing_imports = True

[mypy-crispy_forms.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-django_q.*]
ignore_missing_imports = True
