[tool.poetry]
name = "trustpoint"
version = "0.0.1"
description = "Trustpoint Server Software"
authors = ["TrustPoint-Project"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"
django-tables2 = "^2.7.0"
cryptography = "^42.0.5"
django-crispy-forms = "^2.1"
crispy-bootstrap5 = "^2024.2"
django-ninja = "^1.1.0"
devtools = "^0.12.2"
zeroconf = "^0.132.2"

[tool.poetry.group.dev.dependencies]
sphinx = "^7.2.6"
django-extensions = "^3.2.3"
pyopenssl = "^24.1.0"
werkzeug = "^3.0.2"
furo = "^2024.1.29"
ruff = "^0.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
indent-width = 4


[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101", "ANN401",
    "D203", "D213", "D415",
    "TD003",
    # TODO(Alex): FIX should be added again, after we are departing from the PoC phase
    "FIX",
    "COM812",               # Not compatible with the formatter
    "ISC001"                # Not compatible with the formatter
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"