[project]
name = "trustpoint"
version = "0.1.1"
description = "Trustpoint Server Software"
authors = [{ name = "TrustPoint-Project" }]
requires-python = "~=3.10"
readme = "README.md"
dependencies = [
    "pyasn1>=0.6.1,<0.7",
    "pyasn1-modules>=0.4.1,<0.5",
    "django-crispy-forms~=2.3",
    "crispy-bootstrap5~=2024.10",
    "django-ninja>=1.3.0,<2",
    "django-taggit>=6.1.0,<7",
    "django-filter~=24.3",
    "django-tables2>=2.7.0,<3",
    "pytest-django>=4.9.0,<5",
    "zeroconf>=0.139.0,<0.140",
    "cryptography>=44.0.0,<45",
    "django-stubs>=5.1.2,<6",
    "django-stubs-ext>=5.1.2,<6",
    "django>=5.1.5,<6",
    "behave-html-pretty-formatter>=1.12.3,<2",
    "pytest-cov>=6.0.0,<7",
    "behave-django==1.5.0",
    "behave>=1.2.7.dev6",
    "pre-commit>=4.1.0",
    "ruff>=0.7.4",
]

[dependency-groups]
dev = [
    "sphinx>=8.1.3,<9",
    "sphinxcontrib-plantuml>=0.30,<0.31",
    "devtools>=0.12.2,<0.13",
    "django-extensions>=3.2.3,<4",
    "pyopenssl>=24.2.1,<25",
    "werkzeug>=3.1.3,<4",
    "furo>=2024.8.6,<2025",
    "ruff>=0.7.3,<0.8",
    "pillow>=11.0.0,<12",
    "docutils-stubs>=0.0.22,<0.0.23",
    "mypy>=1.13.0,<2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101", "ANN102", "ANN401",
    "D203", "D213", "D415",
    "TD003",
    # TODO(Alex): FIX should be added again, after we are departing from the PoC phase
    "FIX",
    "COM812",               # Not compatible with the formatter
    "ISC001",               # Not compatible with the formatter
    "S101"
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.12"
strict = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "trustpoint.settings"
