# Generated by Django 5.1.9 on 2025-08-19 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published', models.BooleanField(default=False)),
                ('definition', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(help_text='The node-ID we are currently at (e.g. "step-1")', max_length=100)),
                ('state', models.CharField(choices=[('Starting', 'Starting'), ('Running', 'Running'), ('AwaitingApproval', 'AwaitingApproval'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Starting', max_length=32)),
                ('payload', models.JSONField(help_text='Immutable inputs (eg. CSR fingerprint, CA/Domain/Device IDs)')),
                ('step_contexts', models.JSONField(default=dict, help_text='Mutable per-step storage: e.g. for Approval, email-sent flag; for Timer, deadline timestamp; etc.')),
                ('finalized', models.BooleanField(default=False, help_text='Once true, this instance will never be re-queued or advanced again.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_instances',
                'indexes': [models.Index(fields=['state'], name='workflow_in_state_71d4ab_idx'), models.Index(fields=['finalized'], name='workflow_in_finaliz_c967eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ca_id', models.IntegerField(blank=True, null=True)),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_scopes',
                'unique_together': {('workflow', 'ca_id', 'domain_id', 'device_id')},
            },
        ),
    ]
