# Generated by Django 5.2.8 on 2026-01-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_tp_v0_5_0_dev1'),
        ('pki', '0003_tp_v0_5_0_dev1'),
        ('workflows', '0001_tp_v0_4_0'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowscope',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='workflowscope',
            name='ca_id',
        ),
        migrations.RemoveField(
            model_name='workflowscope',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='workflowscope',
            name='domain_id',
        ),
        migrations.AddField(
            model_name='workflowscope',
            name='ca',
            field=models.ForeignKey(blank=True, db_column='ca_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_scopes', to='pki.issuingcamodel'),
        ),
        migrations.AddField(
            model_name='workflowscope',
            name='device',
            field=models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_scopes', to='devices.devicemodel'),
        ),
        migrations.AddField(
            model_name='workflowscope',
            name='domain',
            field=models.ForeignKey(blank=True, db_column='domain_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_scopes', to='pki.domainmodel'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='aggregated_state',
            field=models.CharField(choices=[('Running', 'Running'), ('AwaitingApproval', 'AwaitingApproval'), ('Approved', 'Approved'), ('Passed', 'Passed'), ('Finalized', 'Finalized'), ('Rejected', 'Rejected'), ('Failed', 'Failed'), ('Aborted', 'Aborted')], default='Running', max_length=32),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requests', to='devices.devicemodel'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='pki.issuingcamodel'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='devices.devicemodel'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='pki.domainmodel'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='current_step',
            field=models.CharField(help_text='Current step id (e.g. "step-1").', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='enrollment_request',
            field=models.ForeignKey(blank=True, help_text='Parent request for enrollment fan-out orchestration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.enrollmentrequest'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='finalized',
            field=models.BooleanField(default=False, help_text='Once true, this instance will never be advanced again.'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='payload',
            field=models.JSONField(help_text='Immutable instance inputs (ids, fingerprint, CSR, etc.).'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='step_contexts',
            field=models.JSONField(default=dict, help_text="Mutable runtime storage (per-step contexts + reserved engine buckets like '$vars')."),
        ),
        migrations.AddConstraint(
            model_name='workflowscope',
            constraint=models.UniqueConstraint(fields=('workflow', 'ca', 'domain', 'device'), name='uq_workflow_scope_workflow_ca_domain_device'),
        ),
    ]
