# Generated by Django 6.0.2 on 2026-02-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0003_tp_v0_5_0_dev1'),
        ('workflows', '0001_tp_v0_4_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerequest',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requests', to='pki.camodel'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='pki.camodel'),
        ),
    ]
