# Generated by Django 5.2.8 on 2025-12-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_tp_v0_4_0_dev1'),
        ('workflows', '0001_tp_v0_4_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerequest',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requests', to='devices.devicemodel'),
        ),
    ]
