# Generated by Django 6.0.2 on 2026-03-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_tp_v0_4_0'),
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustpointAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Cell A Agent 1'.", max_length=120, unique=True, verbose_name='Name')),
                ('agent_id', models.CharField(help_text="Stable identifier sent by the agent in every API request. Must match AGENT_ID in the agent's runtime config.", max_length=120, unique=True, verbose_name='Agent ID')),
                ('certificate_fingerprint', models.CharField(help_text="SHA-256 fingerprint of the agent's mTLS client certificate. Revoke the cert to decommission the agent at the TLS layer.", max_length=64, unique=True, verbose_name='Certificate Fingerprint (SHA-256)')),
                ('capabilities', models.JSONField(default=list, help_text='List of job types this agent supports, e.g. ["wbm_cert_push"]. Used for display and validation; does not restrict API access at runtime.', verbose_name='Capabilities')),
                ('cell_location', models.CharField(blank=True, help_text="Free-text description of the production cell, e.g. 'Building 3 / Cell A'.", max_length=200, verbose_name='Cell Location')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive agents are rejected by the API even if their certificate is still valid.', verbose_name='Active')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300, help_text='How often this agent should call the check-in endpoint. Returned in every check-in response so the agent self-configures. Lower values increase responsiveness; higher values reduce server load.', verbose_name='Poll Interval (seconds)')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Updated on every authenticated API call. Use for liveness monitoring.', null=True, verbose_name='Last Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='The device this agent is associated with. For 1-to-1 agents only one agent per device is allowed; for 1-to-n agents multiple agents may share the same device.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='devices.devicemodel', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Trustpoint Agent',
                'verbose_name_plural': 'Trustpoint Agents',
            },
        ),
        migrations.CreateModel(
            name='WbmCertificateTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='e.g. https://192.168.1.10 — resolved by the agent, not by Trustpoint.', verbose_name='WBM Base URL')),
                ('purpose', models.CharField(choices=[('tls_server', 'TLS Server Certificate'), ('tls_client', 'TLS Client Certificate'), ('ca_bundle', 'CA / Trust-Store Bundle'), ('other', 'Other')], default='tls_server', max_length=20, verbose_name='Slot Purpose')),
                ('slot', models.CharField(blank=True, default='', help_text="Optional device-specific slot name, e.g. 'slot0'.", max_length=80, verbose_name='Slot Identifier')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('renewal_threshold_days', models.PositiveIntegerField(default=30, help_text="Trustpoint will include this target in the agent's check-in response when the currently issued certificate expires within this many days. Set to 0 to only push when explicitly triggered by an operator.", verbose_name='Renewal Threshold (days)')),
                ('push_requested', models.BooleanField(default=False, help_text="Set to True by the operator ('push now') to force a push on the next check-in, regardless of the certificate expiry window. Cleared automatically once the agent picks up the job.", verbose_name='Push Requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent deployed in the production cell that can reach this device.', on_delete=django.db.models.deletion.PROTECT, related_name='wbm_targets', to='agents.trustpointagent', verbose_name='Agent')),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wbm_targets', to='pki.certificateprofilemodel', verbose_name='Certificate Profile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbm_targets', to='devices.devicemodel', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'WBM Certificate Target',
                'verbose_name_plural': 'WBM Certificate Targets',
            },
        ),
        migrations.CreateModel(
            name='WbmJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_csr', 'Pending CSR'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='in_progress', max_length=20, verbose_name='Status')),
                ('key_spec', models.CharField(default='EC_P256', help_text="Algorithm and size for key generation, e.g. 'EC_P256', 'RSA_2048'.", max_length=40, verbose_name='Key Spec')),
                ('subject', models.JSONField(default=dict, help_text='X.509 subject attributes to embed in the CSR, e.g. {"CN": "device.example.com", "O": "Acme"}.', verbose_name='Subject')),
                ('csr_pem', models.TextField(blank=True, help_text='Stored after the agent submits the CSR, before the cert is issued.', verbose_name='CSR (PEM)')),
                ('cert_pem', models.TextField(blank=True, verbose_name='Certificate (PEM)')),
                ('ca_bundle_pem', models.TextField(blank=True, verbose_name='CA Bundle (PEM)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_detail', models.TextField(blank=True, verbose_name='Result Detail')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='agents.wbmcertificatetarget', verbose_name='Certificate Target')),
            ],
            options={
                'verbose_name': 'WBM Job',
                'verbose_name_plural': 'WBM Jobs',
            },
        ),
        migrations.CreateModel(
            name='WbmWorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='Vendor')),
                ('device_family', models.CharField(blank=True, max_length=120, verbose_name='Device Family')),
                ('firmware_hint', models.CharField(blank=True, help_text='Optional firmware version string to help operators select the right profile.', max_length=120, verbose_name='Firmware Hint')),
                ('version', models.CharField(default='1.0', max_length=40, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('profile', models.JSONField(help_text='JSON array of Playwright-style automation steps. Validated on save.', verbose_name='Workflow Profile')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive definitions are hidden from selection but preserved for audit purposes.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WBM Workflow Definition',
                'verbose_name_plural': 'WBM Workflow Definitions',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='wbmcertificatetarget',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='agents.wbmworkflowdefinition', verbose_name='Workflow Definition'),
        ),
        migrations.AlterUniqueTogether(
            name='wbmcertificatetarget',
            unique_together={('device', 'purpose', 'slot')},
        ),
    ]
