# Generated by Django 6.0.2 on 2026-03-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_tp_v0_4_0'),
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this workflow definition.', max_length=200, unique=True, verbose_name='Name')),
                ('profile', models.JSONField(help_text='JSON object containing device metadata and automation steps. Metadata fields: vendor, device_family, firmware_hint, version, description. Steps array contains typed automation steps.', verbose_name='Workflow Profile')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive definitions are hidden from selection but preserved for audit purposes.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Workflow Definition',
                'verbose_name_plural': 'Agent Workflow Definitions',
            },
        ),
        migrations.CreateModel(
            name='AgentCertificateTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('renewal_threshold_days', models.PositiveIntegerField(default=30, help_text="Trustpoint will include this target in the agent's check-in response when the currently issued certificate expires within this many days. Set to 0 to only push when explicitly triggered by an operator.", verbose_name='Renewal Threshold (days)')),
                ('push_requested', models.BooleanField(default=False, help_text="Set to True by the operator ('push now') to force a push on the next check-in, regardless of the certificate expiry window. Cleared automatically once the agent picks up the job.", verbose_name='Push Requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_targets', to='pki.certificateprofilemodel', verbose_name='Certificate Profile')),
                ('device', models.ForeignKey(help_text="The managed device that owns this certificate target. For 1-to-n agents this must be an Agent Managed Device, not the agent device itself. For 1-to-1 agents this must be the agent's own device.", on_delete=django.db.models.deletion.CASCADE, related_name='agent_targets', to='devices.devicemodel', verbose_name='Device')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='agents.agentworkflowdefinition', verbose_name='Workflow Definition')),
            ],
            options={
                'verbose_name': 'Agent Certificate Target',
                'verbose_name_plural': 'Agent Certificate Targets',
            },
        ),
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_csr', 'Pending CSR'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='in_progress', max_length=20, verbose_name='Status')),
                ('key_spec', models.CharField(default='EC_P256', help_text="Algorithm and size for key generation, e.g. 'EC_P256', 'RSA_2048'.", max_length=40, verbose_name='Key Spec')),
                ('subject', models.JSONField(default=dict, help_text='X.509 subject attributes to embed in the CSR, e.g. {"CN": "device.example.com", "O": "Acme"}.', verbose_name='Subject')),
                ('csr_pem', models.TextField(blank=True, help_text='Stored after the agent submits the CSR, before the cert is issued.', verbose_name='CSR (PEM)')),
                ('cert_pem', models.TextField(blank=True, verbose_name='Certificate (PEM)')),
                ('ca_bundle_pem', models.TextField(blank=True, verbose_name='CA Bundle (PEM)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_detail', models.TextField(blank=True, verbose_name='Result Detail')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='agents.agentcertificatetarget', verbose_name='Certificate Target')),
            ],
            options={
                'verbose_name': 'Agent Job',
                'verbose_name_plural': 'Agent Jobs',
            },
        ),
        migrations.CreateModel(
            name='TrustpointAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Cell A Agent 1'.", max_length=120, unique=True, verbose_name='Name')),
                ('agent_id', models.CharField(help_text="Stable identifier sent by the agent in every API request. Must match AGENT_ID in the agent's runtime config.", max_length=120, unique=True, verbose_name='Agent ID')),
                ('certificate_fingerprint', models.CharField(help_text="SHA-256 fingerprint of the agent's mTLS client certificate. Revoke the cert to decommission the agent at the TLS layer.", max_length=64, unique=True, verbose_name='Certificate Fingerprint (SHA-256)')),
                ('capabilities', models.JSONField(default=list, help_text='List of job types this agent supports, e.g. ["wbm_cert_push"]. Used for display and validation; does not restrict API access at runtime.', verbose_name='Capabilities')),
                ('cell_location', models.CharField(blank=True, help_text="Free-text description of the production cell, e.g. 'Building 3 / Cell A'.", max_length=200, verbose_name='Cell Location')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive agents are rejected by the API even if their certificate is still valid.', verbose_name='Active')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300, help_text='How often this agent should call the check-in endpoint. Returned in every check-in response so the agent self-configures. Lower values increase responsiveness; higher values reduce server load.', verbose_name='Poll Interval (seconds)')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Updated on every authenticated API call. Use for liveness monitoring.', null=True, verbose_name='Last Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='For 1-to-1 agents: the device that IS the agent (standalone). For 1-to-n agents: the agent-process device that holds only the domain credential. Application certificates are issued to separate managed-device records.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='devices.devicemodel', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Trustpoint Agent',
                'verbose_name_plural': 'Trustpoint Agents',
            },
        ),
        migrations.AddField(
            model_name='agentcertificatetarget',
            name='agent',
            field=models.ForeignKey(help_text='The agent deployed in the production cell that can reach this device.', on_delete=django.db.models.deletion.PROTECT, related_name='agent_targets', to='agents.trustpointagent', verbose_name='Agent'),
        ),
        migrations.AlterUniqueTogether(
            name='agentcertificatetarget',
            unique_together={('device', 'agent', 'certificate_profile')},
        ),
    ]
