# -------------------------- Wizard state -------------------------------------
EN_APP=false
EN_PG=false
EN_MAILPIT=false
EN_SFTPGO=false
EN_WF2_WORKER=false
EN_PROMETHEUS=false
EN_GRAFANA=false

DB_INTERNAL=true
DB_HOST="$DEF_DB_HOST"
DB_PORT="$DEF_DB_PORT"            # host-mapped port for convenience access
DB_NAME="$DEF_DB_NAME"
DB_USER="$DEF_DB_USER"
DB_PASS="$DEF_DB_PASS"

APP_DB_HOST="$DB_HOST"
APP_DB_PORT="$DB_PORT"
APP_DB_NAME="$DB_NAME"
APP_DB_USER="$DB_USER"
APP_DB_PASS="$DEF_DB_PASS"

TP_TLS_DNS_NAMES_VALUE="$DEF_TP_TLS_DNS_NAMES"
TP_TLS_IPV4_ADDRESSES_VALUE="$DEF_TP_TLS_IPV4_ADDRESSES"
TP_TLS_IPV6_ADDRESSES_VALUE="$DEF_TP_TLS_IPV6_ADDRESSES"
TP_SKIP_SETUP_VALUE="$DEF_TRUSTPOINT_SKIP_SETUP_VALUE"

MAILPIT_SMTP_PORT="$DEF_MAILPIT_SMTP_PORT"
MAILPIT_UI_PORT="$DEF_MAILPIT_UI_PORT"

SFTPGO_SFTP_PORT="$DEF_SFTPGO_SFTP_PORT"
SFTPGO_WEB_PORT="$DEF_SFTPGO_WEB_PORT"
SFTPGO_ADMIN_USER="$DEF_SFTPGO_ADMIN_USER"
SFTPGO_ADMIN_PASS="$DEF_SFTPGO_ADMIN_PASS"

PROMETHEUS_PORT="$DEF_PROMETHEUS_PORT"
GRAFANA_PORT="$DEF_GRAFANA_PORT"
GRAFANA_ADMIN_USER="$DEF_GRAFANA_ADMIN_USER"
GRAFANA_ADMIN_PASS="$DEF_GRAFANA_ADMIN_PASS"

TLS_FP_FOUND=""
TLS_FP_ELAPSED=0
WF2_WORKER_LEASE="$DEF_WF2_WORKER_LEASE"
WF2_WORKER_BATCH="$DEF_WF2_WORKER_BATCH"
WF2_WORKER_SLEEP="$DEF_WF2_WORKER_SLEEP"

# CLI target flags
ONLY_APP=false
ONLY_DB=false
ONLY_MAIL=false
ONLY_SFTP=false
ONLY_WF2_WORKER=false
ONLY_PROMETHEUS=false
ONLY_GRAFANA=false
DEMO_PRESET=""
NOWAIT=false
