# Generated by Django 5.1.9 on 2025-07-22 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published', models.BooleanField(default=False)),
                ('definition', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_node', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Started', 'Started'), ('AwaitingApproval', 'AwaitingApproval'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_instances',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='workflows.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_audit_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ca_id', models.UUIDField(blank=True, null=True)),
                ('domain_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_scopes',
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['state'], name='workflow_in_state_71d4ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowscope',
            unique_together={('workflow', 'ca_id', 'domain_id', 'device_id')},
        ),
    ]
