# Generated by Django 5.1.9 on 2025-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_tp_v0_3_0_dev0'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='step_states',
            field=models.JSONField(default=dict),
        ),
    ]
