# Generated by Django 5.1.9 on 2025-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_tp_v0_3_0_dev0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('error', 'Error'), ('complete', 'Complete')], default='pending', help_text='Overall instance status: pending, error, or complete', max_length=20),
        ),
    ]
