# Generated by Django 5.2.8 on 2026-02-05 10:36

import django.db.models.deletion
import onboarding.models
import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoOnboardingConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pki_protocols', models.PositiveIntegerField(blank=True, default=0, verbose_name='Pki Protocol Bitwise Flag')),
                ('est_password', models.CharField(blank=True, default='', max_length=128, verbose_name='EST Password')),
                ('cmp_shared_secret', models.CharField(blank=True, default='', max_length=128, verbose_name='CMP Shared Secret')),
            ],
            bases=(onboarding.models.AbstractPkiProtocolModel, models.Model),
        ),
        migrations.CreateModel(
            name='OnboardingConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pki_protocols', models.PositiveIntegerField(blank=True, default=0, verbose_name='Pki Protocol Bitwise Flag')),
                ('onboarding_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Onboarded')], default=1, verbose_name='Onboarding Status')),
                ('onboarding_protocol', models.PositiveIntegerField(choices=[(0, 'Manual Onboarding'), (1, 'CMP - IDevID'), (2, 'CMP - Shared Secret'), (3, 'EST - IDevID'), (4, 'EST - Username & Password'), (5, 'AOKI'), (6, 'BRSKI'), (7, 'OPC - GDS Push')], verbose_name='Onboarding Protocol')),
                ('est_password', util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=750, verbose_name='EST Password')),
                ('cmp_shared_secret', util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=750, verbose_name='CMP Shared Secret')),
                ('opc_user', models.CharField(blank=True, default='', max_length=128, verbose_name='OPC User')),
                ('opc_password', util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=750, verbose_name='OPC Password')),
                ('idevid_trust_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idevid_onboarding_configs', to='pki.truststoremodel', verbose_name='IDevID Manufacturer Truststore')),
                ('opc_trust_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opc_onboarding_configs', to='pki.truststoremodel', verbose_name='OPC Server Truststore')),
            ],
            bases=(onboarding.models.AbstractPkiProtocolModel, models.Model),
        ),
    ]
