# Generated by Django 6.0.2 on 2026-02-13 00:38

import django.db.models.deletion
import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='noonboardingconfigmodel',
            name='trust_store',
            field=models.ForeignKey(blank=True, help_text='Trust store containing certificates to verify the remote server', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_onboarding_configs', to='pki.truststoremodel', verbose_name='Trust Store'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='opc_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='OPC Password'),
        ),
    ]
