# Generated by Django 6.0.2 on 2026-02-17 16:33

import util.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='cmp_shared_secret',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='CMP Shared Secret'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='est_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='EST Password'),
        ),
        migrations.AlterField(
            model_name='onboardingconfigmodel',
            name='opc_password',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=345, verbose_name='OPC Password'),
        ),
    ]
