apiVersion: v1
kind: Secret
metadata:
  name: trustpoint-secrets
  namespace: trustpoint
type: Opaque
stringData:
  # Database credentials
  # IMPORTANT: Change these values for production!
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "testing321"
