"""URL configuration for the devices' application."""

from django.urls import path, re_path

from help_pages import devices_help_views
from trustpoint.page_context import (
    DEVICES_PAGE_DEVICES_SUBCATEGORY,
    DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY,
    DEVICES_PAGE_OPC_UA_SUBCATEGORY,
)

from . import views

app_name = 'devices'

urlpatterns = [
    # Main Pages
    path('', views.DeviceTableView.as_view(), name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}'),
    path('opc-ua-gds/', views.OpcUaGdsTableView.as_view(), name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}'),
    path('opc-ua-gds-push/', views.OpcUaGdsPushTableView.as_view(), name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}'),
    # Create Views
    path(
        'create/', views.DeviceCreateChooseOnboardingView.as_view(), name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_create'
    ),
    path(
        'opc-ua-gds/create/',
        views.OpcUaGdsCreateChooseOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_create',
    ),
    path(
        'opc-ua-gds-push/create/',
        views.OpcUaGdsPushCreateChooseOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_create',
    ),
    # Create views using no onboarding
    path(
        'create/no-onboarding/',
        views.DeviceCreateNoOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_create_no_onboarding',
    ),
    path(
        'opc-ua-gds/create/no-onboarding',
        views.OpcUaGdsCreateNoOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_create_no_onboarding',
    ),
    # Create views using onboarding
    path(
        'create/onboarding/',
        views.DeviceCreateOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_create_onboarding',
    ),
    path(
        'opc-ua-gds/create/onboarding',
        views.OpcUaGdsCreateOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_create_onboarding',
    ),
    path(
        'opc-ua-gds-push/create/onboarding',
        views.OpcUaGdsPushCreateOnboardingView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_create_onboarding',
    ),
    # Certificate Lifecycle Management Views
    path(
        'certificate-lifecycle-management/<int:pk>/',
        views.DeviceCertificateLifecycleManagementSummaryView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_certificate_lifecycle_management',
    ),
    path(
        'opc-ua-gds/certificate-lifecycle-management/<int:pk>/',
        views.OpcUaGdsCertificateLifecycleManagementSummaryView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_certificate_lifecycle_management',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/',
        views.OpcUaGdsPushCertificateLifecycleManagementSummaryView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_certificate_lifecycle_management',
    ),
    # Certificate Lifecycle Management - Credential Issuance
    path(
        'certificate-lifecycle-management/<int:pk>/no-onboarding/issue-application-credential/',
        views.DeviceNoOnboardingIssueNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_no_onboarding_clm_issue_application_credential',
    ),
    path(
        'opc-ua-gds/certificate-lifecycle-management/<int:pk>/no-onboarding/issue-application-credential/',
        views.OpcUaGdsNoOnboardingIssueNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_no_onboarding_clm_issue_application_credential',
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/no-onboarding/issue-application-credential/cmp-shared-secret/',
        devices_help_views.DeviceNoOnboardingCmpSharedSecretHelpView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_no_onboarding_cmp_shared_secret_help',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/cmp-shared-secret/'
        ),
        devices_help_views.OpcUaGdsNoOnboardingCmpSharedSecretHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_no_onboarding_cmp_shared_secret_help',
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/no-onboarding/issue-application-credential/est-username-password/',
        devices_help_views.DeviceNoOnboardingEstUsernamePasswordHelpView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_no_onboarding_est_username_password_help',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/est-username-password/'
        ),
        devices_help_views.OpcUaGdsNoOnboardingEstUsernamePasswordHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_no_onboarding_est_username_password_help',
    ),
    path(
        (
            'certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/select-certificate-profile'
        ),
        views.DeviceSelectCertificateProfileNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_no_onboarding_select_certificate_profile',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/select-certificate-profile'
        ),
        views.OpcUaGdsSelectCertificateProfileNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_no_onboarding_select_certificate_profile',
    ),
    path(
        (
            'certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-tls-client-credential/'
        ),
        views.DeviceIssueTlsClientCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_certificate_lifecycle_management_issue_tls_client_credential',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-tls-client-credential/'
        ),
        views.OpcUaGdsIssueTlsClientCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_certificate_lifecycle_management_issue_tls_client_credential',
    ),
    path(
        (
            'certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-tls-server-credential/'
        ),
        views.DeviceIssueTlsServerCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_certificate_lifecycle_management_issue_tls_server_credential',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-tls-server-credential/'
        ),
        views.OpcUaGdsIssueTlsServerCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_certificate_lifecycle_management_issue_tls_server_credential',
    ),
    path(
        (
            'certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-opc-ua-client-credential/'
        ),
        views.DeviceIssueOpcUaClientCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_certificate_lifecycle_management_issue_opc_ua_client_credential',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-opc-ua-client-credential/'
        ),
        views.OpcUaGdsIssueOpcUaClientCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_certificate_lifecycle_management_issue_opc_ua_client_credential',
    ),
    path(
        (
            'certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-opc-ua-server-credential/'
        ),
        views.DeviceIssueOpcUaServerCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_certificate_lifecycle_management_issue_opc_ua_server_credential',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>'
            '/no-onboarding/issue-application-credential/manual/issue-opc-ua-server-credential/'
        ),
        views.OpcUaGdsIssueOpcUaServerCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_certificate_lifecycle_management_issue_opc_ua_server_credential',
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/onboarding/issue-domain-credential/cmp-shared-secret/',
        devices_help_views.DeviceOnboardingDomainCredentialCmpSharedSecretHelpView.as_view(),
        name=(
            f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}'
            '_certificate_lifecycle_management_issue_domain_credential_cmp_shared_secret'
        ),
    ),
    path(
        'opc-ua-gds/certificate-lifecycle-management/<int:pk>/onboarding/issue-domain-credential/cmp-shared-secret/',
        devices_help_views.OpcUaGdsOnboardingDomainCredentialCmpSharedSecretHelpView.as_view(),
        name=(
            f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}'
            '_certificate_lifecycle_management_issue_domain_credential_cmp_shared_secret'
        ),
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/onboarding/issue-domain-credential/est-username-password/',
        devices_help_views.DeviceOnboardingDomainCredentialEstUsernamePasswordHelpView.as_view(),
        name=(
            f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}'
            '_certificate_lifecycle_management_issue_domain_credential_est_username_password'
        ),
    ),
    path(
        'opc-ua-gds/certificate-lifecycle-management/<int:pk>/onboarding/issue-domain-credential/est-username-password/',
        devices_help_views.OpcUaGdsOnboardingDomainCredentialEstUsernamePasswordHelpView.as_view(),
        name=(
            f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}'
            '_certificate_lifecycle_management_issue_domain_credential_est_username_password'
        ),
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/onboarding/issue-application-credential/',
        views.DeviceOnboardingIssueNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_onboarding_clm_issue_application_credential',
    ),
    path(
        'opc-ua-gds/certificate-lifecycle-management/<int:pk>/onboarding/issue-application-credential/',
        views.OpcUaGdsOnboardingIssueNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_onboarding_clm_issue_application_credential',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/onboarding/issue-application-credential/',
        views.OpcUaGdsPushOnboardingIssueNewApplicationCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_onboarding_clm_issue_application_credential',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/onboarding/issue-domain-credential/',
        views.OpcUaGdsPushIssueDomainCredentialView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_onboarding_clm_issue_domain_credential',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/truststore-method-select/',
        views.OpcUaGdsPushTruststoreMethodSelectView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_truststore_method_select',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/discover-server/',
        views.OpcUaGdsPushDiscoverServerView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_discover_server',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/truststore-association/',
        views.OpcUaGdsPushTruststoreAssociationView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_truststore_association',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/onboarding/truststore-associated/',
        devices_help_views.OpcUaGdsPushOnboardingHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_onboarding_truststore_associated_help',
    ),
    path(
        'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/trust-bundle-download/',
        views.OpcUaGdsPushTrustBundleDownloadView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_trust_bundle_download',
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/onboarding/issue-application-credential/cmp-domain-credential/',
        devices_help_views.DeviceApplicationCertificateWithCmpDomainCredentialHelpView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_onboarding_clm_issue_application_credential_cmp_domain_credential',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>/'
            'onboarding/issue-application-credential/cmp-domain-credential/'
        ),
        devices_help_views.OpcUaGdsApplicationCertificateWithCmpDomainCredentialHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_onboarding_clm_issue_application_credential_cmp_domain_credential',
    ),
    path(
        (
            'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/'
            'onboarding/issue-application-credential/opc-ua-gds-push-domain-credential/'
        ),
        devices_help_views.OpcUaGdsPushApplicationCertificateHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_onboarding_clm_issue_application_credential_opc_ua_gds_push_domain_credential',
    ),
    path(
        'certificate-lifecycle-management/<int:pk>/onboarding/issue-application-credential/est-domain-credential/',
        devices_help_views.DeviceApplicationCertificateWithEstDomainCredentialHelpView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_onboarding_clm_issue_application_credential_est_domain_credential',
    ),
    path(
        (
            'opc-ua-gds/certificate-lifecycle-management/<int:pk>/'
            'onboarding/issue-application-credential/est-domain-credential/'
        ),
        devices_help_views.OpcUaGdsApplicationCertificateWithEstDomainCredentialHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_onboarding_clm_issue_application_credential_est_domain_credential',
    ),
    path(
        (
            'opc-ua-gds-push/certificate-lifecycle-management/<int:pk>/'
            'onboarding/issue-application-credential/est-domain-credential/'
        ),
        devices_help_views.OpcUaGdsApplicationCertificateWithEstDomainCredentialHelpView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_onboarding_clm_issue_application_credential_est_domain_credential',
    ),
    # Certificate Lifecycle Management - Downloads
    path(
        'download/<int:pk>/',
        views.DeviceDownloadPageDispatcherView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_download',
    ),
    path(
        'opc-ua-gds/download/<int:pk>/',
        views.OpcUaGdsDownloadPageDispatcherView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_download',
    ),
    path(
        'opc-ua-gds-push/download/<int:pk>/',
        views.OpcUaGdsPushDownloadPageDispatcherView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_download',
    ),
    path(
        'credential/download/<int:pk>/',
        views.DeviceManualCredentialDownloadView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_credential-download',
    ),
    path(
        'opc-ua-gds/credential/download/<int:pk>/',
        views.DeviceManualCredentialDownloadView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_credential-download',
    ),
    path(
        'opc-ua-gds-push/credential/download/<int:pk>/',
        views.DeviceManualCredentialDownloadView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_credential-download',
    ),
    path(
        'credential-download/browser/<int:pk>/',
        views.DeviceBrowserOnboardingOTPView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_browser_otp_view',
    ),
    path(
        'opc-ua-gds/credential-download/browser/<int:pk>/',
        views.OpcUaGdsBrowserOnboardingOTPView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_browser_otp_view',
    ),
    path(
        'certificate/download/<int:pk>/',
        views.DeviceCertificateDownloadView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_certificate-download',
    ),
    path(
        'opc-ua-gds/certificate/download/<int:pk>/',
        views.OpcUaGdsCertificateDownloadView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_certificate-download',
    ),
    path(
        'opc-ua-gds-push/certificate/download/<int:pk>/',
        views.OpcUaGdsPushCertificateDownloadView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_certificate-download',
    ),
    # OPC UA GDS Push Actions
    path(
        'opc-ua-gds-push/<int:pk>/update-trustlist/',
        views.OpcUaGdsPushUpdateTrustlistView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_update_trustlist',
    ),
    path(
        'opc-ua-gds-push/<int:pk>/update-server-certificate/',
        views.OpcUaGdsPushUpdateServerCertificateView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_update_server_certificate',
    ),
    path(
        'credential-download/browser/<int:pk>/cancel',
        views.DeviceBrowserOnboardingCancelView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_browser_cancel',
    ),
    path(
        'credential-download/browser/<int:pk>/cancel',
        views.OpcUaGdsBrowserOnboardingCancelView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_browser_cancel',
    ),
    # browser login and download views
    path('browser/', views.DeviceOnboardingBrowserLoginView.as_view(), name='browser_login'),
    path(
        'browser/credential-download/<int:pk>/',
        views.DeviceBrowserCredentialDownloadView.as_view(),
        name='browser_domain_credential_download',
    ),
    # Revokation views
    path(
        'revoke/<int:pk>/',
        views.DeviceIssuedCredentialRevocationView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_credential_revoke',
    ),
    path(
        'opc-ua-gds/revoke/<int:pk>/',
        views.OpcUaGdsIssuedCredentialRevocationView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_credential_revoke',
    ),
    path(
        'opc-ua-gds-push/revoke/<int:pk>/',
        views.OpcUaGdsPushIssuedCredentialRevocationView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_credential_revoke',
    ),
    re_path(
        r'^revoke-device(?:/(?P<pks>[0-9]+(?:/[0-9]+)*))?/?$',
        views.DeviceBulkRevokeView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_device_revoke',
    ),
    re_path(
        r'^opc-ua-gds/revoke-device(?:/(?P<pks>[0-9]+(?:/[0-9]+)*))?/?$',
        views.DeviceBulkRevokeView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_device_revoke',
    ),
    re_path(
        r'^opc-ua-gds-push/revoke-device(?:/(?P<pks>[0-9]+(?:/[0-9]+)*))?/?$',
        views.DeviceBulkRevokeView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_device_revoke',
    ),
    re_path(
        r'^delete-device(?:/(?P<pks>[0-9]+(?:/[0-9]+)*))?/?$',
        views.DeviceBulkDeleteView.as_view(),
        name=f'{DEVICES_PAGE_DEVICES_SUBCATEGORY}_device_delete',
    ),
    re_path(
        r'^opc-ua-gds/delete-device(?:/(?P<pks>[0-9]+(?:/[0-9]+)*))?/?$',
        views.DeviceBulkDeleteView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_SUBCATEGORY}_device_delete',
    ),
    re_path(
        r'^opc-ua-gds-push/delete-device(?:/(?P<pks>[0-9]+(?:/[0-9]+)*))?/?$',
        views.DeviceBulkDeleteView.as_view(),
        name=f'{DEVICES_PAGE_OPC_UA_GDS_PUSH_SUBCATEGORY}_device_delete',
    ),
]
