"""Django settings for trustpoint project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
import time
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any, ClassVar

import django_stubs_ext
from django.utils.translation import gettext_lazy as _

try:
    APP_VERSION = version('trustpoint')
except PackageNotFoundError:
    APP_VERSION = 'Version not found'

try:
    with Path('/etc/hostname').open('r') as f:
        CONTAINER_ID = f.read().strip()
except FileNotFoundError:
    CONTAINER_ID = 'unknown'


def app_version(_request: Any) -> dict[str, str]:
    """Provide application version and container ID for use in templates.

    Args:
        _request: The HTTP request object (unused).

    Returns:
        dict: A dictionary containing the application version and container ID.
    """
    return {'APP_VERSION': APP_VERSION, 'CONTAINER_ID': CONTAINER_ID}


# Monkeypatching Django, so stubs will work for all generics,
# see: https://github.com/typeddjango/django-stubs
django_stubs_ext.monkeypatch()

# ------------- Paths --------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

LOCALE_PATHS = [BASE_DIR / Path('trustpoint/locale')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / Path('media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [BASE_DIR / Path('static')]

STATIC_ROOT = Path(__file__).parent.parent / Path('collected_static')

LOG_DIR_PATH = BASE_DIR / Path('media/log/')
LOG_DIR_PATH.mkdir(parents=True, exist_ok=True)
LOG_FILE_PATH = LOG_DIR_PATH / Path('trustpoint.log')

BACKUP_FILE_PATH = MEDIA_ROOT / Path('backups')

# Allows all paths that start with:
PUBLIC_PATHS = [
    '/.well-known/cmp',
    '/.well-known/est',
    '/rest',
    '/api',
    '/aoki',
    '/crl',
    '/setup-wizard',
    '/devices/browser',
]


# ------------- Variables --------------

ALLOWED_HOSTS = ['*']
WSGI_APPLICATION = 'trustpoint.wsgi.application'


# mDNS service discovery advertisement
ADVERTISED_HOST = '127.0.0.1'
ADVERTISED_PORT = 443


DOCKER_CONTAINER = False


TRUSTPOINT_PHASE_BOOTSTRAP = 'bootstrap'
TRUSTPOINT_PHASE_OPERATIONAL = 'operational'
TRUSTPOINT_PHASE_AUTO = 'auto'
TRUSTPOINT_VALID_PHASES = frozenset({TRUSTPOINT_PHASE_BOOTSTRAP, TRUSTPOINT_PHASE_OPERATIONAL})
DEFAULT_OPERATIONAL_ENV_FILE = (
    Path('/var/lib/trustpoint/bootstrap/operational.env')
    if DOCKER_CONTAINER
    else REPO_ROOT / 'var' / 'bootstrap' / 'operational.env'
)
TRUSTPOINT_AUTO_OPERATIONAL_ENV_FILE = Path(
    os.getenv('TRUSTPOINT_OPERATIONAL_ENV_FILE', str(DEFAULT_OPERATIONAL_ENV_FILE))
)
TRUSTPOINT_AUTO_OPERATIONAL_READY_FILE = Path(
    os.getenv(
        'TRUSTPOINT_OPERATIONAL_READY_FILE',
        (
            '/var/lib/trustpoint/bootstrap/operational.ready'
            if DOCKER_CONTAINER
            else REPO_ROOT / 'var' / 'bootstrap' / 'operational.ready'
        ),
    )
)


def _configured_trustpoint_phase() -> str:
    """Return the explicitly configured Trustpoint lifecycle phase."""
    configured_phase = os.getenv('TRUSTPOINT_PHASE', TRUSTPOINT_PHASE_OPERATIONAL).strip().lower()
    if configured_phase == TRUSTPOINT_PHASE_AUTO:
        if DOCKER_CONTAINER:
            return (
                TRUSTPOINT_PHASE_OPERATIONAL
                if TRUSTPOINT_AUTO_OPERATIONAL_ENV_FILE.is_file()
                and TRUSTPOINT_AUTO_OPERATIONAL_READY_FILE.is_file()
                else TRUSTPOINT_PHASE_BOOTSTRAP
            )
        return TRUSTPOINT_PHASE_OPERATIONAL
    if configured_phase not in TRUSTPOINT_VALID_PHASES:
        msg = (
            f"Invalid TRUSTPOINT_PHASE={configured_phase!r}. "
            f"Expected one of: {', '.join(sorted({*TRUSTPOINT_VALID_PHASES, TRUSTPOINT_PHASE_AUTO}))}."
        )
        raise RuntimeError(msg)
    return configured_phase


TRUSTPOINT_PHASE = _configured_trustpoint_phase()
TRUSTPOINT_IS_BOOTSTRAP = TRUSTPOINT_PHASE == TRUSTPOINT_PHASE_BOOTSTRAP
TRUSTPOINT_IS_OPERATIONAL = TRUSTPOINT_PHASE == TRUSTPOINT_PHASE_OPERATIONAL
_TRUSTPOINT_PHASE_ENV = os.getenv('TRUSTPOINT_PHASE', '').strip().lower()
TRUSTPOINT_PHASE_CONFIGURED = _TRUSTPOINT_PHASE_ENV in TRUSTPOINT_VALID_PHASES or (
    _TRUSTPOINT_PHASE_ENV == TRUSTPOINT_PHASE_AUTO and DOCKER_CONTAINER and TRUSTPOINT_IS_OPERATIONAL
)
TRUSTPOINT_BOOTSTRAP_USERNAME = os.getenv('TRUSTPOINT_BOOTSTRAP_USERNAME', 'tp-admin')

if TRUSTPOINT_IS_BOOTSTRAP:
    PUBLIC_PATHS.append('/setup-wizard')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not DOCKER_CONTAINER
ADMIN_ENABLED = bool(DEBUG)
DEVELOPMENT_ENV = DEBUG



# Basic SMTP backend
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', default='no-reply@trustpoint.ai')


# Settings for postgreql database
DATABASE_ENGINE = os.environ.get('DATABASE_ENGINE', 'django.db.backends.postgresql')
DATABASE_HOST = os.environ.get('DATABASE_HOST', 'localhost')
DATABASE_PORT = os.environ.get('DATABASE_PORT', '5432')
POSTGRES_DB = os.environ.get('POSTGRES_DB', 'trustpoint_db')
DATABASE_USER = os.environ.get('DATABASE_USER', 'admin')
DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD', 'testing321')
_DEFAULT_OPERATIONAL_DATABASE = 'postgresql' if DOCKER_CONTAINER else 'sqlite'
TRUSTPOINT_OPERATIONAL_DATABASE = os.environ.get(
    'TRUSTPOINT_OPERATIONAL_DATABASE',
    _DEFAULT_OPERATIONAL_DATABASE,
).strip().lower()


# Settomg for email backend
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@trustpoint.de')

# Default: console (safe for dev/showcases)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# If EMAIL_HOST is present, switch to SMTP
_email_host = os.getenv('EMAIL_HOST')  # e.g. "smtp.customer.tld" or "mailpit"
if _email_host:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))

    # Sensible defaults based on port; env can override
    _SMTP_TLS_PORT = 587
    _SMTP_SSL_PORT = 465
    _use_tls_env = os.getenv('EMAIL_USE_TLS')
    _use_ssl_env = os.getenv('EMAIL_USE_SSL')
    EMAIL_USE_TLS = (_use_tls_env.lower() in ('1', 'true', 'yes')) if _use_tls_env else (EMAIL_PORT == _SMTP_TLS_PORT)
    EMAIL_USE_SSL = (_use_ssl_env.lower() in ('1', 'true', 'yes')) if _use_ssl_env else (EMAIL_PORT == _SMTP_SSL_PORT)

    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # auth only if both non-empty
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))


STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
    'dbbackup': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': BACKUP_FILE_PATH,
        },
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'

CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_REDIRECT_URL = 'home:dashboard'
LOGIN_URL = 'users:login'

if TRUSTPOINT_IS_BOOTSTRAP:
    LOGIN_REDIRECT_URL = 'setup_wizard:index'

DJANGO_LOG_LEVEL = 'INFO'

TAGGIT_CASE_INSENSITIVE = True

DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

ROOT_URLCONF = 'trustpoint.urls_bootstrap' if TRUSTPOINT_IS_BOOTSTRAP else 'trustpoint.urls'


# Internationalization
LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
]

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'UTC'

# Application definition
INSTALLED_APPS = [
    'help_pages.apps.HelpPagesConfig',
    'shared.apps.SharedConfig',
    'appsecrets.apps.AppSecretsConfig',
    'setup_wizard.apps.SetupWizardConfig',
    'users.apps.UsersConfig',
    'home.apps.HomeConfig',
    'devices.apps.DevicesConfig',
    'onboarding.apps.OnboardingConfig',
    'pki.apps.PkiConfig',
    'cmp.apps.CmpConfig',
    'est.apps.EstConfig',
    'rest_pki.apps.RestPkiConfig',
    'signer.apps.SignerConfig',
    'aoki.apps.AokiConfig',
    'crypto.apps.CryptoConfig',
    'management.apps.ManagementConfig',
    'trustpoint_core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
    'dbbackup',
    'rest_framework',
    'drf_spectacular',
    'django_q',
    'drf_yasg',
    'workflows2.apps.Workflows2Config',
]

if DEVELOPMENT_ENV and not DOCKER_CONTAINER:
    INSTALLED_APPS.append('django_extensions')
    INSTALLED_APPS.append('behave_django')

MIGRATION_MODULES: dict[str, str | None] = {}

if TRUSTPOINT_IS_OPERATIONAL and TRUSTPOINT_PHASE_CONFIGURED:
    MIGRATION_MODULES['setup_wizard'] = None

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'trustpoint.middleware.SetupWizardRedirectMiddleware',
    'trustpoint.middleware.Workflow2InlineDrainMiddleware',
    'trustpoint.middleware.TrustpointLoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if TRUSTPOINT_IS_BOOTSTRAP:
    MIDDLEWARE = [
        middleware
        for middleware in MIDDLEWARE
        if middleware != 'trustpoint.middleware.Workflow2InlineDrainMiddleware'
    ]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / Path('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'trustpoint.settings.app_version',
                'trustpoint.views.context_processors.trustpoint_runtime_banner',
                'management.context_processors.notification_alerts',
            ],
        },
    },
]

if TRUSTPOINT_IS_BOOTSTRAP:
    TEMPLATES[0]['OPTIONS']['context_processors'] = [
        context_processor
        for context_processor in TEMPLATES[0]['OPTIONS']['context_processors']
        if context_processor != 'management.context_processors.notification_alerts'
    ]


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


def _bootstrap_database_path() -> Path:
    """Return the private SQLite database path used only by bootstrap mode."""
    configured_path = os.getenv('TRUSTPOINT_BOOTSTRAP_DB_PATH')
    if configured_path:
        path = Path(configured_path)
    elif DOCKER_CONTAINER:
        path = Path('/var/lib/trustpoint/bootstrap/bootstrap.sqlite3')
    else:
        path = REPO_ROOT / 'var' / 'bootstrap' / 'bootstrap.sqlite3'

    path.parent.mkdir(parents=True, exist_ok=True)
    return path


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
if TRUSTPOINT_IS_BOOTSTRAP:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(_bootstrap_database_path()),
            'OPTIONS': {'timeout': 20},
        }
    }
elif TRUSTPOINT_OPERATIONAL_DATABASE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': DATABASE_ENGINE,
            'NAME': POSTGRES_DB,
            'USER': DATABASE_USER,
            'PASSWORD': DATABASE_PASSWORD,
            'HOST': DATABASE_HOST,
            'PORT': DATABASE_PORT,
        }
    }
elif TRUSTPOINT_OPERATIONAL_DATABASE == 'sqlite':
    operational_sqlite_path = Path(os.getenv('TRUSTPOINT_OPERATIONAL_SQLITE_PATH', BASE_DIR / 'db.sqlite3'))
    operational_sqlite_path.parent.mkdir(parents=True, exist_ok=True)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(operational_sqlite_path),
            'OPTIONS': {'timeout': 20},
        },
    }
else:
    msg = (
        f"Invalid TRUSTPOINT_OPERATIONAL_DATABASE={TRUSTPOINT_OPERATIONAL_DATABASE!r}. "
        "Expected 'postgresql' or 'sqlite'."
    )
    raise RuntimeError(msg)


# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = 'DEV-ENVIRON-SECRET-KEY-lh2rw0b0z$s9e=!4see)@_8ta_up&ad&m01$i+g5z@nz5u$0wi'  # noqa: S105
else:
    # TODO(AlexHx8472): Use proper docker secrets handling.  # noqa: FIX002
    SECRET_KEY = Path('/etc/trustpoint/secrets/django_secret_key.env').read_text()


class UTCFormatter(logging.Formatter):
    """Custom logging formatter to use UTC time."""

    converter = staticmethod(time.gmtime)


LOGGING = {
    'version': 1,  # Indicates the version of the logging configuration
    'disable_existing_loggers': False,  # Don't disable the default Django logging configuration
    'formatters': {
        'defaultFormatter': {
            '()': UTCFormatter,
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            'datefmt': DATE_FORMAT,
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'defaultFormatter',
        },
        'rotatingFile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'defaultFormatter',
            'filename': LOG_FILE_PATH,
            'maxBytes': 1048576,  # 1MB
            'backupCount': 7,
            'encoding': 'utf8',
        },
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['console', 'rotatingFile'],
        },
    },
}


# User interface config defaults
class UIConfig:
    """User interface configuration defaults."""

    paginate_by: ClassVar[int] = 50
    notifications_paginate_by: ClassVar[int] = 50


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Trustpoint APIs',
    'DESCRIPTION': 'API documentation for Trustpoint project',
    'VERSION': 'v0.0.5',
}

SWAGGER_USE_COMPAT_RENDERERS = False

TASKS = {
    'default': {
        'BACKEND': 'django.tasks.backends.immediate.ImmediateBackend',
    }
}

Q_CLUSTER = {
    'name': 'trustpoint',
    'workers': 2,
    'recycle': 500,
    'timeout': 120,
    'retry': 360,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
}



# HSM storage root:
# - local/dev defaults to <repo-root>/var/hsm
# - deployment can override with TRUSTPOINT_HSM_ROOT=/var/lib/trustpoint/hsm
HSM_ROOT = Path(os.getenv('TRUSTPOINT_HSM_ROOT', REPO_ROOT / 'var' / 'hsm')).resolve()

HSM_CONFIG_DIR = HSM_ROOT / 'config'
HSM_LIB_DIR = HSM_ROOT / 'lib'
HSM_TOKEN_DIR = HSM_ROOT / 'tokens'

HSM_DEFAULT_SOFTHSM_CONFIG_PATH = HSM_CONFIG_DIR / 'softhsm2.conf'
HSM_DEFAULT_USER_PIN_FILE = HSM_CONFIG_DIR / 'user-pin.txt'
HSM_DEFAULT_SO_PIN_FILE = HSM_CONFIG_DIR / 'so-pin.txt'

HSM_DEFAULT_TOKEN_SERIAL_FILE = HSM_CONFIG_DIR / 'token-serial.txt'
HSM_DEFAULT_TOKEN_LABEL = os.getenv('TRUSTPOINT_PKCS11_TOKEN_LABEL', 'Trustpoint-SoftHSM')
HSM_DEFAULT_PKCS11_MODULE_PATH_FILE = HSM_CONFIG_DIR / 'pkcs11-module-path.txt'


def _read_optional_text_file(path: Path) -> str | None:
    """Read a small text file and return stripped content or None."""
    try:
        value = path.read_text(encoding='utf-8').strip()
    except OSError:
        return None
    return value or None


def _first_existing_path(*paths: Path) -> Path | None:
    """Return the first existing path from the provided candidates."""
    for path in paths:
        try:
            path_exists = path.exists()
        except OSError:
            path_exists = False
        if path_exists:
            return path
    return None


_configured_pkcs11_module_path = os.getenv('TRUSTPOINT_PKCS11_MODULE_PATH')
_file_pkcs11_module_path = _read_optional_text_file(HSM_DEFAULT_PKCS11_MODULE_PATH_FILE)

if _configured_pkcs11_module_path:
    HSM_DEFAULT_PKCS11_MODULE_PATH = Path(_configured_pkcs11_module_path)
elif _file_pkcs11_module_path:
    HSM_DEFAULT_PKCS11_MODULE_PATH = Path(_file_pkcs11_module_path)
else:
    HSM_DEFAULT_PKCS11_MODULE_PATH = (
        _first_existing_path(
            # current local/dev default in the Trustpoint container
            Path('/usr/lib/libpkcs11-proxy.so.0'),
            # direct local SoftHSM fallback
            Path('/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so'),
            # final fallback if a library is mounted into the HSM root
            HSM_LIB_DIR / 'libpkcs11.so',
        )
        or (HSM_LIB_DIR / 'libpkcs11.so')
    )

if DEVELOPMENT_ENV and not DOCKER_CONTAINER:
    for directory in (HSM_CONFIG_DIR, HSM_LIB_DIR, HSM_TOKEN_DIR):
        directory.mkdir(parents=True, exist_ok=True)
