"""Views for the devices application."""


from .browser_onboarding import (
    DeviceBrowserOnboardingCancelView,
    DeviceBrowserOnboardingOTPView,
    DeviceOnboardingBrowserLoginView,
    OpcUaGdsBrowserOnboardingCancelView,
    OpcUaGdsBrowserOnboardingOTPView,
)
from .clm import (
    DeviceCertificateLifecycleManagementSummaryView,
    OpcUaGdsCertificateLifecycleManagementSummaryView,
    OpcUaGdsPushCertificateLifecycleManagementSummaryView,
)
from .credential_issuance import (
    DeviceIssueProfileCredentialView,
    DeviceNoOnboardingIssueNewApplicationCredentialView,
    DeviceOnboardingIssueNewApplicationCredentialView,
    DeviceSelectCertificateProfileNewApplicationCredentialView,
    OpcUaGdsIssueProfileCredentialView,
    OpcUaGdsNoOnboardingIssueNewApplicationCredentialView,
    OpcUaGdsOnboardingIssueNewApplicationCredentialView,
    OpcUaGdsPushDiscoverServerView,
    OpcUaGdsPushIssueDomainCredentialView,
    OpcUaGdsPushOnboardingIssueNewApplicationCredentialView,
    OpcUaGdsPushTruststoreAssociationView,
    OpcUaGdsSelectCertificateProfileNewApplicationCredentialView,
)
from .delete import (
    DeviceBulkDeleteView,
    OpcUaGdsBulkDeleteView,
    OpcUaGdsPushBulkDeleteView,
)
from .device_api import DeviceViewSet
from .device_create import (
    DeviceCreateAddOnboardingTypeView,
    DeviceCreateChooseOnboardingView,
    DeviceCreateNoOnboardingView,
    DeviceCreateOnboardingView,
    DeviceCreateOpcUaGdsPushView,
    NamedCurveMissingForEccErrorMsg,
    OpcUaGdsCreateChooseOnboardingView,
    OpcUaGdsCreateNoOnboardingView,
    OpcUaGdsCreateOnboardingView,
    OpcUaGdsPushCreateChooseOnboardingView,
    OpcUaGdsPushCreateOnboardingView,
    PublicKeyInfoMissingErrorMsg,
)
from .download import (
    DeviceBrowserCredentialDownloadView,
    DeviceCertificateDownloadView,
    DeviceDownloadPageDispatcherView,
    DeviceManualCredentialDownloadView,
    OpcUaGdsCertificateDownloadView,
    OpcUaGdsDownloadPageDispatcherView,
    OpcUaGdsPushCertificateDownloadView,
    OpcUaGdsPushDownloadPageDispatcherView,
)
from .gds_push import (
    OpcUaGdsPushCertRenewalSettingsView,
    OpcUaGdsPushUpdateServerCertificateView,
    OpcUaGdsPushUpdateTrustlistView,
    TrustBundleDownloadView,
)
from .revoke import (
    DeviceBulkRevokeView,
    DeviceIssuedCredentialRevocationView,
    OpcUaGdsBulkRevokeView,
    OpcUaGdsIssuedCredentialRevocationView,
    OpcUaGdsPushBulkRevokeView,
    OpcUaGdsPushIssuedCredentialRevocationView,
)
from .tables import (
    DeviceTableView,
    OpcUaGdsTableView,
)

__all__ = [
    'DeviceBrowserCredentialDownloadView',
    'DeviceBrowserOnboardingCancelView',
    'DeviceBrowserOnboardingOTPView',
    'DeviceBulkDeleteView',
    'DeviceBulkRevokeView',
    'DeviceCertificateDownloadView',
    'DeviceCertificateLifecycleManagementSummaryView',
    'DeviceCreateAddOnboardingTypeView',
    'DeviceCreateChooseOnboardingView',
    'DeviceCreateNoOnboardingView',
    'DeviceCreateOnboardingView',
    'DeviceCreateOpcUaGdsPushView',
    'DeviceDownloadPageDispatcherView',
    'DeviceIssueProfileCredentialView',
    'DeviceIssuedCredentialRevocationView',
    'DeviceManualCredentialDownloadView',
    'DeviceNoOnboardingIssueNewApplicationCredentialView',
    'DeviceOnboardingBrowserLoginView',
    'DeviceOnboardingIssueNewApplicationCredentialView',
    'DeviceSelectCertificateProfileNewApplicationCredentialView',
    'DeviceTableView',
    'DeviceViewSet',
    'NamedCurveMissingForEccErrorMsg',
    'OpcUaGdsBrowserOnboardingCancelView',
    'OpcUaGdsBrowserOnboardingOTPView',
    'OpcUaGdsBulkDeleteView',
    'OpcUaGdsBulkRevokeView',
    'OpcUaGdsCertificateDownloadView',
    'OpcUaGdsCertificateLifecycleManagementSummaryView',
    'OpcUaGdsCreateChooseOnboardingView',
    'OpcUaGdsCreateNoOnboardingView',
    'OpcUaGdsCreateOnboardingView',
    'OpcUaGdsDownloadPageDispatcherView',
    'OpcUaGdsIssueProfileCredentialView',
    'OpcUaGdsIssuedCredentialRevocationView',
    'OpcUaGdsNoOnboardingIssueNewApplicationCredentialView',
    'OpcUaGdsOnboardingIssueNewApplicationCredentialView',
    'OpcUaGdsPushBulkDeleteView',
    'OpcUaGdsPushBulkRevokeView',
    'OpcUaGdsPushCertRenewalSettingsView',
    'OpcUaGdsPushCertificateDownloadView',
    'OpcUaGdsPushCertificateLifecycleManagementSummaryView',
    'OpcUaGdsPushCreateChooseOnboardingView',
    'OpcUaGdsPushCreateOnboardingView',
    'OpcUaGdsPushDiscoverServerView',
    'OpcUaGdsPushDownloadPageDispatcherView',
    'OpcUaGdsPushIssueDomainCredentialView',
    'OpcUaGdsPushIssuedCredentialRevocationView',
    'OpcUaGdsPushOnboardingIssueNewApplicationCredentialView',
    'OpcUaGdsPushTruststoreAssociationView',
    'OpcUaGdsPushUpdateServerCertificateView',
    'OpcUaGdsPushUpdateTrustlistView',
    'OpcUaGdsSelectCertificateProfileNewApplicationCredentialView',
    'OpcUaGdsTableView',
    'PublicKeyInfoMissingErrorMsg',
    'TrustBundleDownloadView',
]
