# Generated by Django 5.0.1 on 2024-02-05 15:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import trustpoint.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIssuingCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p12', models.FileField(upload_to='', verbose_name='PKCS#12 File (.p12, .pfx)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IssuingCa',
            fields=[
                ('unique_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(6), trustpoint.validators.validate_isidentifer])),
                ('subject', models.CharField(max_length=1024)),
                ('issuer', models.CharField(max_length=1024)),
                ('not_valid_before', models.DateTimeField()),
                ('not_valid_after', models.DateTimeField()),
                ('root_subject', models.CharField(max_length=1024)),
                ('chain_not_valid_before', models.DateTimeField()),
                ('chain_not_valid_after', models.DateTimeField()),
                ('key_type', models.CharField(choices=[('RSA', 'Rsa'), ('ECC', 'Ecc')], max_length=3)),
                ('key_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65536)])),
                ('curve', models.CharField(blank=True, choices=[('SECP256R1', 'Secp256R1'), ('SECP384R1', 'Secp384R1')], default=None, max_length=10, null=True)),
                ('local_issuing_ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pki.localissuingca')),
            ],
        ),
    ]
