# Generated by Django 5.0.1 on 2024-02-01 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIssuingCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p12', models.FileField(upload_to='', verbose_name='PKCS#12 File (.p12, .pfx)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IssuingCa',
            fields=[
                ('unique_name', models.CharField(max_length=100)),
                ('local_issuing_ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pki.localissuingca')),
            ],
        ),
    ]
