# Generated by Django 5.2.4 on 2025-08-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainmodel',
            name='allow_app_certs_without_domain',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='allow_idevid_registration',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='allow_username_password_registration',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='auto_create_new_device',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='domain_credential_auth',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='username_password_auth',
        ),
        migrations.AlterField(
            model_name='credentialmodel',
            name='certificate_chain',
            field=models.ManyToManyField(blank=True, related_name='credential_certificate_chains', through='pki.CertificateChainOrderModel', through_fields=('credential', 'certificate'), to='pki.certificatemodel'),
        ),
    ]
