# Generated by Django 5.0.1 on 2024-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuingca',
            name='localization',
            field=models.CharField(choices=[('L', 'Local'), ('R', 'Remote')], max_length=1, verbose_name='Localization'),
        ),
    ]
