# Generated by Django 5.1.9 on 2025-07-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainmodel',
            name='allow_app_certs_without_domain',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='allow_idevid_registration',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='allow_username_password_registration',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='auto_create_new_device',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='domain_credential_auth',
        ),
        migrations.RemoveField(
            model_name='domainmodel',
            name='username_password_auth',
        ),
    ]
