# Generated by Django 5.2.7 on 2025-10-31 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=255, unique=True)),
                ('verbose_name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created-At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated-At')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAllowedCertificateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=255)),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='pki.certificateprofilemodel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_profiles', to='devices.devicemodel')),
            ],
            options={
                'unique_together': {('device', 'certificate_profile')},
            },
        ),
        migrations.CreateModel(
            name='DomainAllowedCertificateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=255)),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='pki.certificateprofilemodel')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_profiles', to='pki.domainmodel')),
            ],
            options={
                'unique_together': {('domain', 'alias'), ('domain', 'certificate_profile')},
            },
        ),
    ]
