# Generated by Django 5.0.1 on 2024-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localissuingca',
            name='p12_password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='PKCS#12 Password'),
        ),
    ]
