# Generated by Django 5.2.7 on 2025-11-17 09:25

import django.db.models.deletion
import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_tp_v0_4_0_dev1'),
        ('pki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=255, unique=True)),
                ('verbose_name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created-At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated-At')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='credentialmodel',
            name='private_key',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=116633, verbose_name='Private key (PEM)'),
        ),
        migrations.CreateModel(
            name='PKCS11Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_label', models.CharField(help_text='Label of the HSM token containing the private key', max_length=255, verbose_name='Token Label')),
                ('key_label', models.CharField(help_text='Unique label of the private key within the token', max_length=255, verbose_name='Key Label')),
                ('key_type', models.CharField(choices=[('rsa', 'RSA'), ('ec', 'Elliptic Curve'), ('aes', 'AES')], help_text='Type of the cryptographic key (RSA or EC)', max_length=10, verbose_name='Key Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PKCS#11 Private Key',
                'verbose_name_plural': 'PKCS#11 Private Keys',
                'unique_together': {('token_label', 'key_label')},
            },
        ),
        migrations.AddField(
            model_name='credentialmodel',
            name='pkcs11_private_key',
            field=models.ForeignKey(blank=True, help_text='Reference to HSM-stored private key', null=True, on_delete=django.db.models.deletion.PROTECT, to='pki.pkcs11key', verbose_name='PKCS#11 Private Key'),
        ),
        migrations.CreateModel(
            name='DeviceAllowedCertificateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=255)),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='pki.certificateprofilemodel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_profiles', to='devices.devicemodel')),
            ],
            options={
                'unique_together': {('device', 'certificate_profile')},
            },
        ),
        migrations.CreateModel(
            name='DomainAllowedCertificateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=255)),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='pki.certificateprofilemodel')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_profiles', to='pki.domainmodel')),
            ],
            options={
                'unique_together': {('domain', 'alias'), ('domain', 'certificate_profile')},
            },
        ),
    ]
