# Generated by Django 5.2.8 on 2026-01-15 13:16

import django.db.models.deletion
import trustpoint.logger
import util.encrypted_fields
import util.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuingcamodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issuingcamodel',
            name='crl_pem',
        ),
        migrations.RemoveField(
            model_name='issuingcamodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='issuingcamodel',
            name='last_crl_issued_at',
        ),
        migrations.RemoveField(
            model_name='issuingcamodel',
            name='unique_name',
        ),
        migrations.RemoveField(
            model_name='issuingcamodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='credentialmodel',
            name='private_key',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=116633, verbose_name='Private key (PEM)'),
        ),
        migrations.CreateModel(
            name='KeylessCaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(help_text='The CA certificate', on_delete=django.db.models.deletion.PROTECT, related_name='certificate_only_ca', to='pki.certificatemodel', verbose_name='CA Certificate')),
            ],
            options={
                'verbose_name': 'Keyless CA',
                'verbose_name_plural': 'Keyless CAs',
            },
            bases=(trustpoint.logger.LoggerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(help_text='Unique identifier for this CA', max_length=100, unique=True, validators=[util.field.UniqueNameValidator()], verbose_name='CA Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this CA is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('issuing_ca_ref', models.OneToOneField(blank=True, help_text='The issuing CA (can issue certificates)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ca', to='pki.issuingcamodel', verbose_name='Issuing CA')),
                ('parent_ca', models.ForeignKey(blank=True, help_text='The parent CA in the hierarchy (issuer of this CA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_cas', to='pki.camodel', verbose_name='Parent CA')),
                ('keyless_ca', models.OneToOneField(blank=True, help_text='The keyless CA (certificate without private key)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ca', to='pki.keylesscamodel', verbose_name='Keyless CA')),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'ordering': ['unique_name'],
            },
            bases=(trustpoint.logger.LoggerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crl_pem', models.TextField(help_text='The Certificate Revocation List in PEM format', verbose_name='CRL in PEM format')),
                ('crl_number', models.PositiveBigIntegerField(blank=True, help_text='The CRL number from the CRL extension', null=True, verbose_name='CRL Number')),
                ('this_update', models.DateTimeField(help_text='The thisUpdate field from the CRL', verbose_name='This Update')),
                ('next_update', models.DateTimeField(blank=True, help_text='The nextUpdate field from the CRL', null=True, verbose_name='Next Update')),
                ('validity_period', models.DurationField(blank=True, help_text='The duration between this_update and next_update (how long this CRL is valid)', null=True, verbose_name='Validity Period')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current active CRL for the CA', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('ca', models.ForeignKey(help_text='The CA that issued this CRL', on_delete=django.db.models.deletion.CASCADE, related_name='crls', to='pki.camodel', verbose_name='Certificate Authority')),
            ],
            options={
                'verbose_name': 'Certificate Revocation List',
                'verbose_name_plural': 'Certificate Revocation Lists',
                'ordering': ['-this_update'],
                'indexes': [models.Index(fields=['ca', '-this_update'], name='pki_crlmode_ca_id_ba124c_idx'), models.Index(fields=['ca', 'is_active'], name='pki_crlmode_ca_id_e556ea_idx')],
                'unique_together': {('ca', 'crl_number')},
            },
            bases=(trustpoint.logger.LoggerMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='camodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issuing_ca_ref__isnull', True), ('keyless_ca__isnull', False)), models.Q(('issuing_ca_ref__isnull', False), ('keyless_ca__isnull', True)), _connector='OR'), name='exactly_one_ca_type'),
        ),
    ]
