# Generated by Django 5.2.7 on 2025-10-22 13:04

import util.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_tp_v0_3_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialmodel',
            name='private_key',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=116633, verbose_name='Private key (PEM)'),
        ),
    ]
