# Generated by Django 5.2.8 on 2026-01-12 10:42

import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_tp_v0_4_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingcamodel',
            name='crl_number',
            field=models.PositiveIntegerField(default=0, verbose_name='CRL Number'),
        ),
        migrations.AlterField(
            model_name='credentialmodel',
            name='private_key',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=116633, verbose_name='Private key (PEM)'),
        ),
    ]
