# Generated by Django 5.2.8 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_tp_v0_5_0_dev1'),
        ('pki', '0003_tp_v0_5_0_dev1'),
        ('workflows', '0002_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssuingCaModel',
        ),
        migrations.AddIndex(
            model_name='crlmodel',
            index=models.Index(fields=['ca', '-this_update'], name='pki_crlmode_ca_id_ba124c_idx'),
        ),
        migrations.AddIndex(
            model_name='crlmodel',
            index=models.Index(fields=['ca', 'is_active'], name='pki_crlmode_ca_id_e556ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crlmodel',
            unique_together={('ca', 'crl_number')},
        ),
    ]
