# Generated by Django 6.0.2 on 2026-02-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0004_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercredentialmodel',
            name='owner_credential_type',
            field=models.IntegerField(choices=[(0, 'Local'), (1, 'Remote EST'), (2, 'Remote CMP')], default=0, help_text='How the DevOwnerID certificate is acquired.', verbose_name='Credential Type'),
        ),
    ]
