# Generated by Django 5.2.8 on 2026-02-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0004_tp_v0_4_0_dev1'),
        ('pki', '0004_tp_v0_5_0_dev1'),
    ]

    operations = [
    ]
