# Generated by Django 5.2.8 on 2026-02-09 10:05

import util.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0004_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialmodel',
            name='private_key',
            field=util.encrypted_fields.EncryptedCharField(blank=True, default='', max_length=116633, verbose_name='Private key (PEM)'),
        ),
    ]
