# Generated by Django 5.2.8 on 2026-01-20 08:16

import django.db.models.deletion
import util.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0004_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crlmodel',
            name='ca',
            field=models.ForeignKey(blank=True, help_text='The CA that issued this CRL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crls', to='pki.camodel', verbose_name='Certificate Authority'),
        ),
    ]
