# Generated by Django 6.0.2 on 2026-02-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0005_owner_credential_add_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='idevidreferencemodel',
            name='dev_owner_id_certificate',
            field=models.ForeignKey(blank=True, help_text='The DevOwnerID certificate whose SAN contained this IDevID reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idevid_refs', to='pki.certificatemodel', verbose_name='DevOwnerID Certificate'),
        ),
    ]
