# Generated by Django 6.0.2 on 2026-02-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('pki', '0003_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='issuing_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pki.camodel'),
        ),
        migrations.AlterField(
            model_name='weakecccurve',
            name='oid',
            field=models.CharField(choices=[('1.3.132.0.8', 'SECP160R1'), ('1.2.840.10045.3.1.1', 'SECP192R1'), ('1.3.132.0.33', 'SECP224R1'), ('1.3.132.0.10', 'SECP256K1')], max_length=64, unique=True),
        ),
    ]
