# Generated by Django 6.0.2 on 2026-02-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('pki', '0003_tp_v0_5_0_dev1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='issuing_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pki.camodel'),
        ),
    ]
