# Generated by Django 5.2.1 on 2025-05-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_mode', models.CharField(choices=[('0', 'Testing env'), ('1', 'Basic'), ('2', 'Medium'), ('3', 'High'), ('4', 'Highest')], default='1', max_length=6)),
                ('auto_gen_pki', models.BooleanField(default=False)),
                ('auto_gen_pki_key_algorithm', models.CharField(choices=[('RSA2048SHA256', 'RSA2048'), ('RSA4096SHA256', 'RSA4096'), ('SECP256R1SHA256', 'SECP256R1')], default='RSA2048SHA256', max_length=24)),
            ],
        ),
    ]
