# Generated by Django 5.1.9 on 2025-08-25 06:58

import django.db.models.deletion
import trustpoint.logger
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0002_tp_v0_3_0_dev1'),
        ('settings', '0002_tp_v0_3_0_dev0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupoptions',
            name='password',
            field=models.CharField(blank=True, help_text='Plain-text password for SFTP.', max_length=128, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='PKCS11Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsm_type', models.CharField(choices=[('softhsm', 'SoftHSM'), ('physical', 'Physical HSM')], default='softhsm', help_text='Type of HSM (SoftHSM or Physical)', max_length=10, verbose_name='HSM Type')),
                ('label', models.CharField(help_text='Token label in SoftHSM', max_length=100, unique=True, verbose_name='Label')),
                ('slot', models.PositiveIntegerField(help_text='Slot number in SoftHSM', verbose_name='Slot')),
                ('module_path', models.CharField(default='/usr/lib/softhsm/libsofthsm2.so', help_text='Path to PKCS#11 module library', max_length=255, verbose_name='Module Path')),
                ('encrypted_dek', models.BinaryField(blank=True, help_text='Symmetric key encrypted by the PKCS#11 private key', max_length=512, null=True, verbose_name='Encrypted Data Encryption Key (DEK)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('kek', models.ForeignKey(blank=True, help_text='Associated key encryption key stored in this token', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pki.pkcs11key', verbose_name='Key Encryption Key (KEK)')),
            ],
            options={
                'verbose_name': 'PKCS#11 Token',
                'verbose_name_plural': 'PKCS#11 Tokens',
            },
            bases=(models.Model, trustpoint.logger.LoggerMixin),
        ),
    ]
