# Generated by Django 5.1.9 on 2025-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_tp_v0_3_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkcs11token',
            name='bek_encrypted_dek',
            field=models.BinaryField(blank=True, help_text='Symmetric key encrypted by the PKCS#11 private key', max_length=512, null=True, verbose_name='Encrypted Data Encryption Key (DEK)'),
        ),
    ]
