# Generated by Django 5.1.9 on 2025-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_tp_v0_3_0_dev1'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='container_build_id',
            field=models.CharField(blank=True, default='', help_text='Container build ID or hash', max_length=64),
        ),
    ]
