"""Sets up a Trustpoint test environment for AOKI IDevID-based onboarding testing.

This command re-uses the certificates generated by ``aoki_gen_test_certs`` and creates:

- A dedicated RSA-2048 Root CA ``aoki-root-ca`` and Issuing CA ``aoki-issuing-ca``.
- A dedicated domain ``aoki`` linked to the new issuing CA.
- An IDevID truststore ``AokiIDevIDTruststore`` containing the generated IDevID CA certificate
  (``idevid_ca.pem``).
- A DevID registration pattern ``AokiIDevIDRegistration`` linking the truststore to the ``aoki``
  domain, with a serial number regex pattern matching the test serial number ``4212``.
- An owner credential ``AokiOwnerCred`` (LOCAL / file-import mode) built from the generated
  DevOwnerID certificate (``owner_id.pem``), its private key (``owner_id_pk.pem``), and the
  Owner CA certificate chain (``ownerid_ca.pem``).

Run ``aoki_gen_test_certs`` first to generate the required certificate files, or let this
command generate them automatically when they are missing.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.asymmetric.ed448 import Ed448PrivateKey
from cryptography.hazmat.primitives.serialization import load_pem_private_key
from django.core.management import call_command
from django.core.management.base import BaseCommand
from trustpoint_core.serializer import CredentialSerializer

from pki.management.commands.base_commands import CertificateCreationCommandMixin
from pki.models import CaModel, CertificateModel, DevIdRegistration, DomainModel
from pki.models.credential import OwnerCredentialModel
from pki.models.truststore import TruststoreModel, TruststoreOrderModel
from trustpoint.logger import LoggerMixin

if TYPE_CHECKING:
    from typing import Any

CERTS_DIR = (Path(__file__).resolve().parents[2] / 'tests' / 'certs').resolve()

IDEVID_CA_CERT_PATH = CERTS_DIR / 'idevid_ca.pem'
OWNER_ID_CERT_PATH = CERTS_DIR / 'owner_id.pem'
OWNER_ID_KEY_PATH = CERTS_DIR / 'owner_id_pk.pem'
OWNER_CA_CERT_PATH = CERTS_DIR / 'ownerid_ca.pem'

IDEVID_TRUSTSTORE_UNIQUE_NAME = 'AokiIDevIDTruststore'
DEVID_REGISTRATION_UNIQUE_NAME = 'AokiIDevIDRegistration'
OWNER_CRED_UNIQUE_NAME = 'AokiOwnerCred'

ISSUING_CA_UNIQUE_NAME = 'aoki-issuing-ca'
DOMAIN_UNIQUE_NAME = 'aoki'

# Matches the TEST_SERIAL_NUMBER defined in aoki_gen_test_certs
TEST_SERIAL_NUMBER = '4212'
SERIAL_NUMBER_PATTERN = TEST_SERIAL_NUMBER

# ruff: noqa: T201  # use of print is fine in management commands


class Command(CertificateCreationCommandMixin, LoggerMixin, BaseCommand):
    """Sets up a Trustpoint test environment for AOKI IDevID-based onboarding testing."""

    help = (
        'Creates a dedicated AOKI issuing CA and domain, then populates the IDevID truststore, '
        'DevID registration pattern, and DevOwnerID owner credential for AOKI IDevID-based '
        'onboarding testing. Run ``aoki_gen_test_certs`` first to generate the required certs.'
    )

    def log_and_stdout(self, message: str, level: str = 'info') -> None:
        """Log a message and print it to stdout.

        :param message: The message to log and print.
        :param level: The log level (``'info'``, ``'warning'``, or ``'error'``).
        """
        print(message)
        if level == 'warning':
            self.logger.warning(message)
        elif level == 'error':
            self.logger.error(message)
        else:
            self.logger.info(message)

    def handle(self, *args: Any, **kwargs: Any) -> None:
        """Execute the command.

        Ensures default certificate profiles exist, generates test certificates if they are
        missing, creates the dedicated AOKI issuing CA and domain, then creates the IDevID
        truststore, DevID registration pattern, and owner credential in Trustpoint.

        :param args: Additional positional arguments (unused).
        :param kwargs: Additional keyword arguments (unused).
        """
        del args, kwargs  # Unused

        call_command('create_default_cert_profiles')
        self._ensure_certs_exist()

        issuing_ca = self._get_or_create_issuing_ca()
        domain = self._get_or_create_domain(issuing_ca)
        truststore = self._get_or_create_idevid_truststore()
        self._get_or_create_devid_registration(truststore, domain)
        self._get_or_create_owner_credential()

        self.log_and_stdout('\n=== AOKI IDevID test environment ready ===')
        self.log_and_stdout(f'  Issuing CA:              {ISSUING_CA_UNIQUE_NAME}')
        self.log_and_stdout(f'  Domain:                  {DOMAIN_UNIQUE_NAME}')
        self.log_and_stdout(f'  IDevID Truststore:       {IDEVID_TRUSTSTORE_UNIQUE_NAME}')
        self.log_and_stdout(f'  DevID Registration:      {DEVID_REGISTRATION_UNIQUE_NAME}')
        self.log_and_stdout(f'    Serial number pattern: {SERIAL_NUMBER_PATTERN}')
        self.log_and_stdout(f'    Domain:                {domain.unique_name}')
        self.log_and_stdout(f'  Owner Credential:        {OWNER_CRED_UNIQUE_NAME}')

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _ensure_certs_exist(self) -> None:
        """Run ``aoki_gen_test_certs`` if any required certificate file is missing.

        :raises FileNotFoundError: If a required certificate file is still missing after
            running the generator command.
        """
        required_files = [
            IDEVID_CA_CERT_PATH,
            OWNER_ID_CERT_PATH,
            OWNER_ID_KEY_PATH,
            OWNER_CA_CERT_PATH,
        ]
        if not all(f.exists() for f in required_files):
            self.log_and_stdout('Test certificates not found - running aoki_gen_test_certs...')
            call_command('aoki_gen_test_certs')

        for path in required_files:
            if not path.exists():
                msg = f'Required certificate file not found: {path}'
                raise FileNotFoundError(msg)

    def _get_or_create_issuing_ca(self) -> CaModel:
        """Return an existing AOKI issuing CA or create a new one."""
        if CaModel.objects.filter(unique_name=ISSUING_CA_UNIQUE_NAME).exists():
            self.log_and_stdout(
                f'Issuing CA "{ISSUING_CA_UNIQUE_NAME}" already exists, skipping creation.'
            )
            return CaModel.objects.get(unique_name=ISSUING_CA_UNIQUE_NAME)

        root_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        issuing_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

        root_cn = f'{ISSUING_CA_UNIQUE_NAME} Root CA'
        root_cert, _ = self.create_root_ca(
            cn=root_cn,
            private_key=root_key,
            hash_algorithm=hashes.SHA256(),
            validity_days=7300,
        )
        issuing_cert, _ = self.create_issuing_ca(
            issuer_private_key=root_key,
            issuer_cn=root_cn,
            subject_cn=ISSUING_CA_UNIQUE_NAME,
            private_key=issuing_key,
            hash_algorithm=hashes.SHA256(),
            validity_days=3650,
        )
        issuing_ca = self.save_issuing_ca(
            issuing_ca_cert=issuing_cert,
            chain=[root_cert],
            private_key=issuing_key,
            unique_name=ISSUING_CA_UNIQUE_NAME,
        )
        self.log_and_stdout(f'Created issuing CA "{ISSUING_CA_UNIQUE_NAME}".')
        return issuing_ca

    def _get_or_create_domain(self, issuing_ca: CaModel) -> DomainModel:
        """Return an existing AOKI domain or create a new one linked to the given issuing CA."""
        domain, created = DomainModel.objects.get_or_create(unique_name=DOMAIN_UNIQUE_NAME)
        if created:
            domain.issuing_ca = issuing_ca
            domain.save()  # triggers _add_default_profiles()
            self.log_and_stdout(f'Created domain "{DOMAIN_UNIQUE_NAME}".')
        else:
            self.log_and_stdout(f'Domain "{DOMAIN_UNIQUE_NAME}" already exists, skipping creation.')
        return domain

    def _get_or_create_idevid_truststore(self) -> TruststoreModel:
        """Return an existing IDevID truststore or create one from the generated IDevID CA cert.

        Reads ``idevid_ca.pem`` from the test certs directory and stores it as a
        :class:`~pki.models.truststore.TruststoreModel` with intended usage ``IDEVID``.

        :returns: The :class:`~pki.models.truststore.TruststoreModel` for
            ``AokiIDevIDTruststore``.
        """
        if TruststoreModel.objects.filter(unique_name=IDEVID_TRUSTSTORE_UNIQUE_NAME).exists():
            self.log_and_stdout(
                f'IDevID truststore "{IDEVID_TRUSTSTORE_UNIQUE_NAME}" already exists, skipping creation.'
            )
            return TruststoreModel.objects.get(unique_name=IDEVID_TRUSTSTORE_UNIQUE_NAME)

        idevid_ca_cert = x509.load_pem_x509_certificate(IDEVID_CA_CERT_PATH.read_bytes())
        cert_model = self._save_certificate(idevid_ca_cert)

        truststore = TruststoreModel(
            unique_name=IDEVID_TRUSTSTORE_UNIQUE_NAME,
            intended_usage=TruststoreModel.IntendedUsage.IDEVID,
        )
        truststore.save()
        TruststoreOrderModel.objects.create(
            trust_store=truststore,
            certificate=cert_model,
            order=0,
        )
        self.log_and_stdout(f'Created IDevID truststore "{IDEVID_TRUSTSTORE_UNIQUE_NAME}".')
        return truststore

    def _get_or_create_devid_registration(
        self, truststore: TruststoreModel, domain: DomainModel
    ) -> DevIdRegistration:
        """Return an existing DevID registration or create one linking truststore and domain.

        The serial number pattern is set to ``4212``, which is the test serial number
        embedded in the IDevID Subject Serial Number by ``aoki_gen_test_certs``.

        :param truststore: The IDevID truststore to link to the registration.
        :param domain: The domain to associate with the registration.
        :returns: The :class:`~pki.models.DevIdRegistration` for
            ``AokiIDevIDRegistration``.
        """
        if DevIdRegistration.objects.filter(unique_name=DEVID_REGISTRATION_UNIQUE_NAME).exists():
            self.log_and_stdout(
                f'DevID registration "{DEVID_REGISTRATION_UNIQUE_NAME}" already exists, skipping creation.'
            )
            return DevIdRegistration.objects.get(unique_name=DEVID_REGISTRATION_UNIQUE_NAME)

        registration = DevIdRegistration(
            unique_name=DEVID_REGISTRATION_UNIQUE_NAME,
            truststore=truststore,
            domain=domain,
            serial_number_pattern=SERIAL_NUMBER_PATTERN,
        )
        registration.full_clean()
        registration.save()
        self.log_and_stdout(
            f'Created DevID registration "{DEVID_REGISTRATION_UNIQUE_NAME}" '
            f'(domain: {domain.unique_name}, pattern: {SERIAL_NUMBER_PATTERN}).'
        )
        return registration

    def _get_or_create_owner_credential(self) -> OwnerCredentialModel:
        """Return an existing owner credential or create one from the generated DevOwnerID files.

        Reads ``owner_id.pem`` (certificate), ``owner_id_pk.pem`` (private key), and
        ``ownerid_ca.pem`` (CA chain) from the test certs directory and stores them as a
        LOCAL :class:`~pki.models.credential.OwnerCredentialModel`.

        :returns: The :class:`~pki.models.credential.OwnerCredentialModel` for
            ``AokiOwnerCred``.
        """
        if OwnerCredentialModel.objects.filter(unique_name=OWNER_CRED_UNIQUE_NAME).exists():
            self.log_and_stdout(
                f'Owner credential "{OWNER_CRED_UNIQUE_NAME}" already exists, skipping creation.'
            )
            return OwnerCredentialModel.objects.get(unique_name=OWNER_CRED_UNIQUE_NAME)

        owner_cert = x509.load_pem_x509_certificate(OWNER_ID_CERT_PATH.read_bytes())
        raw_key = load_pem_private_key(OWNER_ID_KEY_PATH.read_bytes(), password=None)
        owner_ca_cert = x509.load_pem_x509_certificate(OWNER_CA_CERT_PATH.read_bytes())

        if not isinstance(
            raw_key,
            (rsa.RSAPrivateKey, ec.EllipticCurvePrivateKey, Ed25519PrivateKey, Ed448PrivateKey),
        ):
            msg = f'Unsupported private key type: {type(raw_key)}'
            raise TypeError(msg)

        credential_serializer = CredentialSerializer(
            private_key=raw_key,
            certificate=owner_cert,
            additional_certificates=[owner_ca_cert],
        )

        owner_credential = OwnerCredentialModel.create_new_owner_credential(
            unique_name=OWNER_CRED_UNIQUE_NAME,
            credential_serializer=credential_serializer,
        )
        self.log_and_stdout(f'Created owner credential "{OWNER_CRED_UNIQUE_NAME}".')
        return owner_credential

    @staticmethod
    def _save_certificate(cert: x509.Certificate) -> CertificateModel:
        """Save a certificate to the database, returning an existing entry if present.

        :param cert: The certificate to save.
        :returns: The :class:`~pki.models.CertificateModel` for the certificate.
        """
        fingerprint = cert.fingerprint(hashes.SHA256()).hex().upper()
        try:
            return CertificateModel.objects.get(sha256_fingerprint=fingerprint)
        except CertificateModel.DoesNotExist:
            return CertificateModel.save_certificate(cert)
