@startuml
    package "GitHub" {
      [Repository]
      [Actions]
    }

    package "CI/CD Pipelines" {
      [Codecov]
      [Behave]
      [MyPy]
      [Pytest]
      [Ruff]
    }

    [Repository] --> [CI/CD Pipelines] : Triggers Pipelines

    Codecov --> [Codecov Service] : Upload Coverage
    Behave --> [Actions] : Update Badge
    [Codecov Service] --> [Actions] : Update Badge
    MyPy --> [Actions] : Update Badge
    Pytest --> [Actions] : Update Badge
    Ruff --> [Actions] : Update Badge

    [Actions] --> [Repository] : Display Badges in README
@enduml