name: Setup Environment
description: Checks out code and installs the current uv version and it's dependencies defined inside the pyproject.toml file.
runs:
  using: "composite"
  steps:
    - name: Install and setup uv
      uses: astral-sh/setup-uv@v5  # Sets up `uv` package manager.
      with:
        enable-cache: true  # Caches `uv` installation for faster runs.
        version: "0.6.4"  # Use a fixed version for consistency.
        cache-dependency-glob: "uv.lock" # Invalidate cache when the lockfile changes.

    - name: Set up Python
      uses: actions/setup-python@v5  # Sets up Python environment.
      with:
        python-version-file: "pyproject.toml"  # Ensures the correct Python version is used.

    - name: Run database migrations # Resets the database before running tests.
      if: inputs.run_migrations == true  # Only run migrations if input is true.
      shell: bash
      run: |
        echo "y" | uv run trustpoint/manage.py reset_db  
