#!/usr/bin/env bash

start_worker() {
  remove_compose_service trustpoint-worker
  remove_container "$WF2_WORKER_NAME"
  local soft_hsm_args=()
  if state_has softhsm; then
    soft_hsm_args+=(
      -v "$LOCAL_HSM_CONFIG_DIR:$LOCAL_HSM_CONTAINER_CONFIG_DIR"
      -v "$LOCAL_HSM_TOKEN_DIR:$LOCAL_HSM_CONTAINER_TOKEN_DIR"
      -e TRUSTPOINT_HSM_ROOT="$LOCAL_HSM_CONTAINER_ROOT"
      -e SOFTHSM2_CONF="$LOCAL_HSM_CONTAINER_SOFTHSM2_CONF"
      -e TRUSTPOINT_LOCAL_HSM_ENABLED=1
      -e TRUSTPOINT_LOCAL_HSM_TOKEN_LABEL="$LOCAL_HSM_TOKEN_LABEL"
      -e TRUSTPOINT_LOCAL_HSM_TOKEN_SERIAL="$(local_hsm_value TRUSTPOINT_LOCAL_HSM_TOKEN_SERIAL)"
      -e TRUSTPOINT_LOCAL_HSM_PROFILE_NAME="$LOCAL_HSM_PROFILE_NAME"
      -e TRUSTPOINT_LOCAL_HSM_MODULE_PATH="$LOCAL_HSM_CONTAINER_MODULE_PATH"
      -e TRUSTPOINT_LOCAL_HSM_USER_PIN_FILE="$LOCAL_HSM_CONTAINER_CONFIG_DIR/user-pin.txt"
      -e TRUSTPOINT_LOCAL_HSM_CONFIG_ENV_VAR=SOFTHSM2_CONF
      -e TRUSTPOINT_LOCAL_HSM_SOFTHSM2_CONF="$LOCAL_HSM_CONTAINER_SOFTHSM2_CONF"
    )
  fi
  start_container "$WF2_WORKER_NAME" "${soft_hsm_args[@]}" \
    -e TRUSTPOINT_PHASE=auto -e TRUSTPOINT_SERVICE_ROLE=worker \
    -e POSTGRES_DB="$DB_NAME" -e DATABASE_USER="$DB_USER" -e DATABASE_PASSWORD="$DB_PASS" \
    -e DATABASE_HOST="$APP_DB_HOST" -e DATABASE_PORT="$APP_DB_PORT" \
    -e WORKFLOWS2_WORKER_ID="$WF2_WORKER_ID" -e WORKFLOWS2_WORKER_LEASE="$WF2_WORKER_LEASE" \
    -e WORKFLOWS2_WORKER_BATCH="$WF2_WORKER_BATCH" -e WORKFLOWS2_WORKER_SLEEP="$WF2_WORKER_SLEEP" \
    "$APP_IMAGE"
  ok 'Workflows2 worker started'
}
