# .github/workflows/backup-restore.yml
name: Backup & Restore TrustPoint

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Base name for the backup (".dump.gz" will be appended)'
        required: false
        type: string
        default: 'from_outside'

jobs:
  backup-and-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build TrustPoint image
        run: docker compose build trustpoint

      - name: Start TrustPoint container
        run: docker compose up -d

      - name: Apply migrations (in-container)
        run: docker compose exec -T trustpoint \
              uv run trustpoint/manage.py migrate --noinput

      - name: Fill demo data (in-container)
        run: |
          docker compose exec -T trustpoint \
            uv run trustpoint/manage.py add_domains_and_devices
          docker compose exec -T trustpoint \
            uv run trustpoint/manage.py tls_cred

      - name: Create backup (in-container)
        run: docker compose exec -T trustpoint \
             uv run trustpoint/manage.py trustpointbackup --filename ${{ inputs.artifact_name }}

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}.dump.gz
          path: trustpoint/media/backups/${{ inputs.artifact_name }}.dump.gz

      - name: Stop & remove old container
        run: docker compose down --volumes --remove-orphans

      - name: Start fresh TrustPoint container
        run: docker compose up -d

      - name: Apply migrations on fresh container
        run: docker compose exec -T trustpoint \
              uv run trustpoint/manage.py migrate --noinput

      - name: Download backup artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}.dump.gz
          path: trustpoint/media/backups/

      - name: Restore backup (in-container)
        run: |
          docker compose exec -T trustpoint \
            uv run trustpoint/manage.py dbrestore -z --noinput \
              -I trustpoint/media/backups/${{ inputs.artifact_name }}.dump.gz
          docker compose exec -T trustpoint \
            uv run trustpoint/manage.py trustpointrestore

      - name: Cleanup local backup file
        run: rm -f trustpoint/media/backups/${{ inputs.artifact_name }}.dump.gz
