name: Behave Tests

on:
  workflow_call:
    inputs:
      feature_file:
        description: 'Feature file to test'
        required: true
        type: string

jobs:
  run-behave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.6.3"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run database migrations
        run: |
          echo "y" | uv run trustpoint/manage.py reset_db

      - name: Run Behave Tests and Generate HTML Report for ${{ inputs.feature_file }}.feature
        run: |
          uv run trustpoint/manage.py behave \
          trustpoint/features/${{ inputs.feature_file }}.feature

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.feature_file }}-html-report
          path: behave-report.html