name: Behave Feature Tests

on:
  push:
    paths:
      - trustpoint/features/**
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies with Poetry
      run: |
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: true
        POETRY_VIRTUALENVS_IN_PROJECT: true

    - name: Run database migrations
      run: |
        echo "y" | poetry run python trustpoint/manage.py reset_db
        poetry run python trustpoint/manage.py collectstatic --noinput

    - name: Run Behave Tests and Generate HTML Report
      run: |
        poetry run behave trustpoint/features/ --no-capture -f behave_html_pretty_formatter:PrettyHTMLFormatter -D behave.formatter.html-pretty.title_string="TrustPoint Test Report" -o behave-report.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: behave-html-report
        path: behave-report.html