name: Codecov upload

on: [ pull_request ]

jobs:
  codecov-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.12

      - name: Run database migrations
        run: |
          echo "y" | uv run trustpoint/manage.py reset_db

      - name: Run Pytest with Coverage
        run: uv run pytest --cov=trustpoint --cov-report=xml trustpoint/

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
