name: Tests / Code Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codecov-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action
        with:
          run_migrations: true

      - name: Run Pytest with Coverage
        run: uv run pytest --cov=trustpoint --cov-report=xml --junitxml=junit.xml -o junit_family=legacy trustpoint/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./junit.xml

