name: Core Tests

on:
  push:
    paths:
      - trustpoint/core/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Run unit tests for the file builder module
        uses: quantco/pytest-action@v2
        with:
          report-title: Unit-Test Report for the file builder module
          custom-pytest:
            uv run pytest

      - name: Run unit tests for the serializer module
        uses: quantco/pytest-action@v2
        with:
          report-title: Unit-Test Report for the serializer module
          custom-pytest:
            uv run pytest