name: Tests / Docker Compose

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .env file
        run: cp .env.example .env

      - name: Run Docker compose
        uses: hoverkraft-tech/compose-action@v3.0.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build --wait"

      - name: Test Home Page with curl (self-signed HTTPS)
        run: |
          echo "Checking health of the HTTPS endpoint with self-signed cert..."

          URL="https://127.0.0.1/"

          for i in {1..20}; do
            http_response=$(curl -k -L -s -o response.txt -w "%{http_code}" "$URL") || true

            if [ "$http_response" = "200" ]; then
              echo "✅ Success on attempt $i"
              break
            else
              echo "⏳ Attempt $i failed with HTTP code $http_response, retrying..."
              sleep 3
            fi
          done

          echo "Server returned: $http_response" >> "$GITHUB_STEP_SUMMARY"

          if [ "$http_response" != "200" ]; then
            echo "❌ Healthcheck failed." >> "$GITHUB_STEP_SUMMARY"
            echo "Response body:" >> "$GITHUB_STEP_SUMMARY"
            cat response.txt >> "$GITHUB_STEP_SUMMARY"
            exit 1
          else
            echo "✅ Healthcheck passed." >> "$GITHUB_STEP_SUMMARY"
            echo "Response body:" >> "$GITHUB_STEP_SUMMARY"
            cat response.txt >> "$GITHUB_STEP_SUMMARY"
          fi
