name: Trustpoint pipeline

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trustpoint:${{ github.sha }} --tag trustpoint:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push the Docker image
      run: |
        docker tag trustpoint:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/trustpoint:${{ github.sha }}
        docker tag trustpoint:latest ${{ secrets.DOCKER_HUB_USERNAME }}/trustpoint:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/trustpoint:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/trustpoint:latest