name: EST Protocol Tests

on:
  push:
    branches:
      - "dev_est_test"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies with Poetry
      run: |
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: true
        POETRY_VIRTUALENVS_IN_PROJECT: true

    - name: Run database migrations
      run: |
        echo "y" | poetry run python trustpoint/manage.py reset_db
        poetry run python trustpoint/manage.py collectstatic --noinput

    - name: Run unit and integration tests
      run: |
        poetry run pytest trustpoint/est/tests/

    - name: Run Behave Tests and Generate HTML Report
      run: |
        mkdir -p reports
        poetry run behave -f behave_html_formatter -o reports/behave-report.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: behave-html-report
        path: reports/behave-report.html

#    - name: Run Behave tests
#      run: |
#        poetry run behave -f html -o behave-report.html

#    - name: Generate Allure reports
#      run: |
#        mkdir -p trustpoint/reports/allure
#        poetry run behave trustpoint/features/ --no-capture --format allure_behave.formatter:AllureFormatter -o trustpoint/reports/allure
#
#    - name: Install Allure CLI
#      run: |
#        wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.zip
#        unzip allure-2.32.0.zip
#        sudo mv allure-2.32.0 /opt/allure
#        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
#
#    - name: Generate Allure report
#      run: |
#        allure generate trustpoint/reports/allure -o trustpoint/reports/allure-report --clean

#    - name: Upload results
#      uses: actions/upload-artifact@v3
#      with:
#        name: Report
#        path: behave-report.html
