name: MyPy

on: [ pull_request ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Run MyPy
        run: uv run mypy .