name: Code Quality / MyPy

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  mypy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action

      - name: Run MyPy
        run: uv run mypy .