name: Pytest

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action
        with:
          run_migrations: true

      - name: Run Pytest and create reports
        run: |
          mkdir -p reports
          uv run pytest \
          --md-report-flavor github \
          --md-report-color never \
          --html=reports/pytest-report.html \
          --junitxml=reports/junit-report.xml \
          trustpoint/ 

      - name: Display Summary in GitHub Actions even if tests fail
        if: always()
        run: |
          echo "<details><summary>Pytest Report</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat "md-report.md" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Upload Test Reports even if tests fail
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: pytest-reports
          path: reports/

      - name: Render the report to the PR
        uses: marocchino/sticky-pull-request-comment@v3  # Posts test results as a comment on PRs.
        if: always()  # Always runs.
        with:
          header: test-report
          recreate: true  # Replaces previous test reports to keep PR comments clean.
          path: md-report.md  # Posts the markdown test report in the PR.