name: Pytest Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Run tests with coverage
        run: |
          uv run pytest \
          --junitxml=core-pytest-report.xml \
          --cov=trustpoint \
          --cov-report=html \
          --cov-report=term-missing \
          --html=core-pytest-report.html \
          --self-contained-html \
          trustpoint/core/tests/ | tee core-pytest-output.log

      - name: Upload pytest reports for the core module
        uses: actions/upload-artifact@v4
        with:
          name: core-pytest-report
          path: |
            core-pytest-report.html

      - name: Display Summary in Job Output
        run: |
          echo "## Pytest Results for the core module :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat core-pytest-output.log >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY