name: Code Quality / Ruff

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-action

      - name: Run Ruff Linting
        run: uv run ruff check .
