name: Ruff

# Trigger this workflow on pull requests to ensure tests are executed before merging.
on: [pull_request]

jobs:
  setup:
    uses: ./.github/workflows/setup-env.yml  # Call the reusable setup workflow.

  ruff:
    needs: setup  # Ensures setup runs first.
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for compatibility and performance.

    steps:
      - name: Run Ruff Linting
        run: ruff check .

      - name: Upload Ruff Logs
        if: failure()  # Only upload logs if the step fails.
        uses: actions/upload-artifact@v4
        with:
          name: ruff-report
          path: ruff-report.txt
