name: Setup Environment

on:
  workflow_call:
    inputs:
      run_migrations:
        description: "Run database migrations before tests"
        required: false
        type: boolean
        default: false  # By default, migrations are not run.

jobs:
  setup:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures the repository code is available.

      - name: Install and setup uv
        uses: astral-sh/setup-uv@v5  # Sets up `uv` package manager.
        with:
          enable-cache: true  # Caches `uv` installation for faster runs.
          version: "0.6.3"  # Use a fixed version for consistency.
          cache-dependency-glob: "uv.lock" # Invalidate cache when the lockfile changes.

      - name: Set up Python
        uses: actions/setup-python@v5  # Sets up Python environment.
        with:
          python-version-file: "pyproject.toml"  # Ensures the correct Python version is used.

      - name: Run database migrations # Resets the database before running tests.
        if: inputs.run_migrations == true  # Only run migrations if input is true.
        run: |
          echo "y" | uv run trustpoint/manage.py reset_db  
