name: Test docker compose build

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run docker compose action
#        https://github.com/adambirds/docker-compose-action
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "test-container"
          test-command: "npm test"
